### ISSUE TITLE
基于自然语言交互技术的智能文本识别

### ISSUE THREAD

**Issue by anaivebird** [rubickCenter/rubick#101]
**您的功能请求是否与问题相关？ 请简单描述.**
比如用户输入 我要看ip，模型自动生成ip addr show，标注数据让大模型few shot就行了

**请描述一下您想要的解决方案**
text2sql模型可以把文本变成sql语句，直接把输出改成命令，让我们的用户数据每天自动标注，然后训练nlp模型

**描述你考虑过的替代方案**
我打算自己来开发这个功能

**Comment by linonetwo** [comment]
搞个类似 https://github.com/lblblong/mossgpt-utools 的，然后搞个选项，把结果再作为 rubick 输入就好了

**Comment by linonetwo** [comment]
@anaivebird 不打算自己来开发这个功能了？
