### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by yufeixuan** [rubickCenter/rubick#103]
**描述一下这个bug**
运行后无法输入任何文字，无法使用

**复现方式**
node 14.19.1
yarn install
yarn run electron:build

**截图**
![image](https://user-images.githubusercontent.com/8575535/163975494-b8a0f67e-73b4-4d4d-9b56-8de44cbe9c2a.png)

**Comment by muwoo** [comment]
@yufeixuan f12 可以打开rubick控制台，看看报了啥错

**Comment by yufeixuan** [comment]
F12没有任何反应，双击就变全屏
![image](https://user-images.githubusercontent.com/8575535/163978035-8aa78bf3-970e-4787-a0d9-0953559c5f85.png)

**Comment by yufeixuan** [comment]
看不明白是什么错误
![image](https://user-images.githubusercontent.com/8575535/163980066-867224ab-991d-48b0-b821-45cc758b69b0.png)

**Comment by muwoo** [comment]
@yufeixuan 你的rubick是什么版本的

**Comment by yufeixuan** [comment]
直接拉取的master分支
![image](https://user-images.githubusercontent.com/8575535/163980397-d346564d-4f93-4af1-b927-6b85b96f6bb6.png)

**Comment by muwoo** [comment]
@yufeixuan 临时修复可以先尝试删除`vue.config.js` 中的 `extract-file-icon` ：
```js
   externals: [
        'pouchdb',
   --  'extract-file-icon'
    ],
```

**Comment by muwoo** [comment]
`extract-file-icon` 是 `windows` 用到的一个包，理论上你在 `mac` 下会自动过滤掉的，如果还不行的话再试着删除 `package.json` 中的 `extract-file-icon`。再重新 install node_modules

**Comment by lixiaoming-bit** [comment]
extract-file-icon
这个包 我在mac os （inter)上安装和 windows 10 上安装都报错 只有M1的mac上安装成功了

**Comment by muwoo** [comment]
extract-file-icon 这个包mac上可以干掉，win 上依赖 `windows-build-tools` 这个来编译 `C++`。windows上如何安装 `windows-build-tools` 可以搜索一下，很多文档
