### ISSUE TITLE
执行 npm run elecetron:serve 没有看到报错，electron 闪一下就退出了，这个是什么原因造成的？博主有碰到这种情况吗？执行 npm run electron:build 是可以成功的

### ISSUE THREAD

**Issue by buck005** [rubickCenter/rubick#107]
## 任何开发建议、交流学习都可以
![image](https://user-images.githubusercontent.com/22255895/166117292-586305cb-d7f9-465d-9550-72945737f054.png)

**Comment by buck005** [comment]
![image](https://user-images.githubusercontent.com/22255895/166118621-a2b7351d-6f6e-4c22-a002-a881758eb8c7.png)
![image](https://user-images.githubusercontent.com/22255895/166118583-220d2738-8122-4e8f-bdbc-980e90365899.png)

本地可以跑起来，但是如上图，不能任何操作，我看 package.json文件里面入口"main": "background.js", background.js项目中不用写的？

**Comment by muwoo** [comment]
> ## 任何开发建议、交流学习都可以
> ![image](https://user-images.githubusercontent.com/22255895/166117292-586305cb-d7f9-465d-9550-72945737f054.png)

可能是你已经开启了一个 `rubick` 应用程序，默认情况下，只能开启一个 `rubick` 应用程序。所以你可以退出一下已经开启的 `rubick` 再启动一下试试

**Comment by muwoo** [comment]
> ![image](https://user-images.githubusercontent.com/22255895/166118621-a2b7351d-6f6e-4c22-a002-a881758eb8c7.png) ![image](https://user-images.githubusercontent.com/22255895/166118583-220d2738-8122-4e8f-bdbc-980e90365899.png)

选中 rubick 窗口后快捷键 ：option+command+i 打开Chrome控制台，看看报错信息

**Comment by adwardlzq** [comment]
![](https://pops.oss-cn-beijing.aliyuncs.com/mdimg/WX20220718-215057.png)

**Comment by tenviy** [comment]
一样的问题，刚拉下来的代码，估计代码有问题，或者环境

**Comment by tenviy** [comment]
![bug](https://user-images.githubusercontent.com/30422748/180806873-7a01e215-d50c-4e4a-911f-8e5054508b3e.png)

**Comment by aComputerGeek** [comment]
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/25359239/182762306-4f0d9743-520e-4aca-8a3b-fd97e989222c.png">
在本地调试了下， 好像是这两个文件的语法问题😒

**Comment by muwoo** [comment]
@aComputerGeek @tenviy vue版本的问题，降级到 v3.0.0 。可能是vue升级带来的问题，
