### ISSUE TITLE
因 Gitee 私有化导致的问题

### ISSUE THREAD

**Issue by muwoo** [rubickCenter/rubick#108]
本来数据库接口是通过 gitee 的raw 的方式来请求gitee仓库的JSON。最近因为Gitee 私有化后，仓库变成了私有仓库，造成了访问权限问题。

当我提交开源申请的时候，又出现了新问题：

![image](https://user-images.githubusercontent.com/21073039/169227925-c8d60202-4f03-44bd-99b8-5f02feaccbfb.png)

看来 gitee 白嫖被发现了😭。这可能需要升级一下rubick换一下白嫖的地址了~

**Comment by loocao** [comment]
可以提交到github，使用github的加速代理，比如：https://doc.fastgit.org/zh-cn/guide.html#%E5%AF%B9%E4%BA%8E-raw-%E7%9A%84%E4%BB%A3%E7%90%86

**Comment by cjhgit** [comment]
可否把 rubick-database 这个仓库同步到 Github？

**Comment by muwoo** [comment]
@cjhgit  @loocao   已修复
