### ISSUE TITLE
长按右键弹出超级面板时候系统右键菜单也会出现

### ISSUE THREAD

**Issue by DogeVenci** [rubickCenter/rubick#11]
长按右键弹出超级面板时候系统右键菜单也会出现，utools 超级面板长按时候不会出现原本的系统右键菜单，感觉是用窗体遮挡

**Comment by muwoo** [comment]
@DogeVenci 尝试了一下，应该不是，因为目前只能通过`iohook` 来做鼠标事件的监听，原生右击事件要早于 `ioHook` 的 mousedown 事件，所以要使用 `iohook` 做监听，在右击一刹那弹出窗口，那就会闪烁。所以可能还是需要原生类似于浏览器那样可以 `prevent default ` 就再好不过了。具体事件思路还在想

**Comment by DogeVenci** [comment]
看utools的代码应该是调用了BrowserWindow.getNativeWindowHandle()拿到窗口句柄传给它的C++ Addons处理了

**Comment by muwoo** [comment]
@DogeVenci 你哪来的 utools 代码🤣

**Comment by DogeVenci** [comment]
@muwoo electron应用打包后都在resources/app.asar 用asar解开就看到 有点代码被压缩混淆还是能看得懂的 。
另外utools插件也是asar打包的 electron可以直接读取asar里面文件

**Comment by DogeVenci** [comment]
Windows 上用API Monitor看到utools的C++ Addons调用SetWindowHookEx来设置全局鼠标钩子了，Mac上也应该是比较底层的拦截鼠标事件方法，linux只能用中键调用超级面板，暂时没找到跨平台的开源库能拦截鼠标事件的，这个功能留到以后再说吧。

**Comment by DogeVenci** [comment]
@muwoo iohook.disableClickPropagation() 可以拦截🤣

**Comment by muwoo** [comment]
@DogeVenci 不行的，这个是全局事件，而且触发机制比原生的晚。

**Comment by muwoo** [comment]
目前只能用`iohook` 的 `disableClickPropagation`  来阻止默认右击事件弹窗，但是带来的的副作用是用户正常的右击操作也会被阻止，无法恢复。

如果不用长按右击唤起超级面板，那可以用按鼠标中键的方式，但是鼠标中键 macos 上通过触摸板无法触发。

所以如果有比较好的方案可以帮忙解决这个问题。

**Comment by hecmay** [comment]
@muwoo 现在是不支持超级面板了是吗？刚在MacOS上试了最新的rubick，长按右键什么都没有出现

**Comment by muwoo** [comment]
改为 Ctrl + W 快捷键呼起超级面板
