### ISSUE TITLE
mac打包报错

### ISSUE THREAD

**Issue by Hiram-Wong** [rubickCenter/rubick#115]
环境：
system：Apple M1 Pro 13.0 Beta版(22A5321d)
app：2.0.4-beta.3

问题：
在运行yarn electron:build时会遇到如下报错Exit code: ENOENT. spawn /usr/bin/python ENOENT，主要原因是苹果取消了python2作为系统环境
![](https://s3.bmp.ovh/imgs/2022/08/12/88708d3b1475c905.png)

解决办法：
在packeage.json中添加如下变量  "resolutions" : { "vue-cli-plugin-electron-builder/electron-builder": "^23.0.3" },
然后yarn install并yarn electron:build
以此来构建arm架构包
![](https://s3.bmp.ovh/imgs/2022/08/12/289dddebb0d48fc3.png)

最后附上打包的m1包：
https://musetransfer.com/s/sytpj0om4（有效期至2023年8月12日）｜密码：2536｜【Muse】你有一份文件待查收，请点击链接获取文件

**Comment by muwoo** [comment]
@Hiram-Wong 非常感谢
