### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by uchief** [rubickCenter/rubick#116]
**描述一下这个bug**
安装依赖之后运行 npm run serve 报错如下

系统版本：mac-12.5
node：v16.16.0
npm：v8.16.0
yarn: v1.22.19

<img width="1636" alt="image" src="https://user-images.githubusercontent.com/94058904/184323355-01601c2e-ebe3-4b3e-a099-07e9814b36c0.png">

**复现方式**
1. clone代码
2. yarn install
3. npm run serve

**预期行为**
清晰简明地描述了您预期的发生。

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。

**Comment by Hiram-Wong** [comment]
为什么要混用yarn和npm

**Comment by uchief** [comment]
> 



> 

yarn run dev 之后也一样，和是否混用没关系

**Comment by AdamCaoQAQ** [comment]
按照 #142 修改配置可修复报错

**Comment by hhstore** [comment]
- 合着, 没几个人编译运行过这个项目啊?!
- 挺搞笑. 
- 编译都通不过的项目. 是认真的吗?!
- 除了LS同学 PR 改的报错点. 
- 还缺失了一堆依赖包. MacOS 环境.
