### ISSUE TITLE
考虑出插件市场吗

### ISSUE THREAD

**Issue by ayuayue** [rubickCenter/rubick#117]
## utools的会员价格跟最近更新后剪贴板等基础功能都需要会员身份才能使用。
是否可以新增一个插件市场的功能，再开源的基础上由开发者或者个人进行上传及维护，如果只是个人使用并且无法很好的数据同步还是满足不了很多用户的，当然这些也需要付出费用及精力。

**Comment by zqhong** [comment]
支持 WebDAV 同步插件和数据就好。

这里有个草案规划：
https://github.com/rubickCenter/rubick/discussions/57

**Comment by ayuayue** [comment]
> 支持 WebDAV 同步插件和数据就好。
> 
> 这里有个草案规划： #57

❤️
