### ISSUE TITLE
插件下载时报错

### ISSUE THREAD

**Issue by FxRayHughes** [rubickCenter/rubick#121]
**描述一下这个bug**
下载超级剪贴板时进行报错

**复现方式**
1. 打开插件列表点击超级剪贴板

**预期行为**
清晰简明地描述了您预期的发生。

**截图**
![image](https://user-images.githubusercontent.com/25192142/184791771-afd0b215-a32f-438a-904a-5b124f757c5a.png)

**Comment by muwoo** [comment]
@FxRayHughes 目前rubick依赖npm进行插件安装，需要用户本地有node环境，win下安装node环境文档：https://juejin.cn/post/6892790243687137287  rubick 正在内部集成node环境，后续将会修复这个问题
