### ISSUE TITLE
win11一安装插件就报错

### ISSUE THREAD

**Issue by gangxiaoji** [rubickCenter/rubick#122]
![image](https://user-images.githubusercontent.com/22111267/184792242-8bc60d63-7839-4579-90fb-821ac2fadb03.png)

**Comment by muwoo** [comment]
[#121 ]

**Comment by muwoo** [comment]
@gangxiaoji 目前rubick依赖npm进行插件安装，需要用户本地有node环境，win下安装node环境文档：https://juejin.cn/post/6892790243687137287 rubick 正在内部集成node环境，后续将会修复这个问题

**Comment by muwoo** [comment]
rubick 操作指南的文档上有说明：https://rubickcenter.github.io/rubick/guide/#%E5%89%8D%E8%A8%80

**Comment by gangxiaoji** [comment]
好的,还有个问题,我设置了全局快捷键呼出超级剪切板,但是一次呼出后,点击别的地方自动隐藏后,再次使用剪切板快捷键就没办法呼出了,必须要使用呼出面板的快捷键才行

**Comment by gangxiaoji** [comment]
超级面板也无法正常使用

**Comment by gangxiaoji** [comment]
还有就是面板呼出的位置是否可以调整,对于我来说有点靠下,但是好像没有记忆功能,每次都会从初始位置呼出,刚刚安装,不知道是否是我没找到设置,辛苦您了

**Comment by jiaxinonly** [comment]
我在win11上已经安装nodejs18，但是还是一安装插件就报错，根本无法使用，另外希望能够优化下应用查找功能，比如输入wx，就能找到微信应用，而且有些应用安装后搜索不到，比如typora，毕竟原来使用utools的人，基本都是重度使用应用快速启动和剪切板这2个功能

**Comment by muwoo** [comment]
最新版本已修复
