### ISSUE TITLE
为什么我安装了之后，插件市场是空的啊

### ISSUE THREAD

**Issue by nianshuzhi** [rubickCenter/rubick#123]

**Comment by Jonnyan404** [comment]
我是苹果m1    nodejs环境已转了，一样空白

**Comment by wxhaor** [comment]
+1

**Comment by nzlov** [comment]
换一个插件仓库

**Comment by mofazhe** [comment]
应该是[gitee](https://gitee.com/monkeyWang/rubick-database)仓库访问不了了，请问有替代的么

**Comment by iamzhaoxin** [comment]
> +1

+1

**Comment by xiaohai-78** [comment]
+100

**Comment by xiaohai-78** [comment]
> 换一个插件仓库

可以换哪个？

**Comment by besich** [comment]
你确认下你的rubick2是哪个版本的？如果是默认版本的，我的win版本的也有这个问题，换成最新的beta3就好了

**Comment by li-kexue** [comment]
> 你确认下你的rubick2是哪个版本的？如果是默认版本的，我的win版本的也有这个问题，换成最新的beta3就好了

我目前下载的就是beta3也不可以

**Comment by muwoo** [comment]
@nianshuzhi 已修复
