### ISSUE TITLE
提交homebrew-cask支持

### ISSUE THREAD

**Issue by zhongjun96** [rubickCenter/rubick#125]
已经提交RP [Add Rubick 2.0.4](https://github.com/Homebrew/homebrew-cask/pull/129899)
合并后可使用 `brew install rubick` 安装。
后续更新维护此文件即可。

**Comment by zhongjun96** [comment]
麻烦看看能否加上签名？ @muwoo 
https://github.com/Homebrew/homebrew-cask/pull/129899#issuecomment-1232520720

**Comment by muwoo** [comment]
@zhongjun96 刚看到，麻烦再提个pr？

**Comment by zhongjun96** [comment]
已经重新提交PR
https://github.com/Homebrew/homebrew-cask/pull/160294

**Comment by zhongjun96** [comment]
> 已经重新提交 PR [Homebrew/homebrew-cask#160294](https://github.com/Homebrew/homebrew-cask/pull/160294)

ARM版本没签名，被拒绝了
