### ISSUE TITLE
按下Backspace时窗口变形

### ISSUE THREAD

**Issue by xjzh123** [rubickCenter/rubick#131]
**描述一下这个bug**

**复现方式**
1. Windows11系统下，启动2.0.4-beta3版rubick
2. 用Alt+R唤出
3. （与rubick窗口互动使焦点在rubick输入框）
4. 按下Backspace键
窗口会向上变形。

**预期行为**
窗口大小不变

**截图**
![](https://s3.bmp.ovh/imgs/2022/08/18/ea5e537f69110438.gif)

**Comment by 1129921824** [comment]
还挺申请的，issue可以关了，新版本了
