### ISSUE TITLE
ui与utools过度相似可能涉及版权问题说明

### ISSUE THREAD

**Issue by Cypas** [rubickCenter/rubick#136]
## 任何开发建议、交流学习都可以
作者有和utools官方就软件ui的事情联系过吗?
utools目前已越加商业化，且utools近期对部分常用插件，如剪贴板开始进行了收费，一定程度上会导致用户流失和迁移到这边，这对utools来说可能并不是好事
rubick软件ui存在对utools的致敬，但uttols官方随时都可以以软件界面盗版进行起诉rubick，这是很无奈的事实
最好的处理方式还是尽早改掉软件ui

**Comment by qw4096** [comment]
附议，界面逻辑可以不用改，换个皮肤就可以了

**Comment by Katzeee** [comment]
附议，由于utools开始商业化转移到此

**Comment by jurnlee** [comment]
强烈附议。那种最终开源软件被下架的案例也不是没有过，那样的结局都不是大家想看到的~

**Comment by lt-123** [comment]
附议

**Comment by KevinCattt** [comment]
附议 致敬utools 这种精神和出发点是好的 但要小心侵权的风险

**Comment by zi4dbek** [comment]
强烈附议，这么好的软件，被告下架谁也不想看见 @rubickCenter

**Comment by muwoo** [comment]
收到建议，我已经开始着手修改交互和UI了

**Comment by muwoo** [comment]
rubick 交互调整产品文档：https://www.yuque.com/muwoo/ifugfw/pqxecfim66h7ak7h?singleDoc#%20%E3%80%8Arubick%20%E9%A1%B5%E9%9D%A2%E4%BA%A4%E4%BA%92%E8%AE%BE%E8%AE%A1%E9%87%8D%E6%9E%84%E3%80%8B

**Comment by muwoo** [comment]
感谢所有小伙伴的建议，rubick 致力于开源社区建设，无意与 utools 竞争，同时也为了避免可能产生的 UI 侵权风险，rubick 4.x 版本开始，花了 4000 块钱（众筹了 ¥2000+） 外包了一个交互设计师进行 UI 交互重构。目前 rubick 4.x 已发布。可以前往下载体验。

## 致谢
感谢所有参与 UI 重构众筹的小伙伴，谢谢你们

![image](https://github.com/rubickCenter/rubick/assets/21073039/212cff2c-7ea7-423c-aa89-cc63c493fbe4)
