### ISSUE TITLE
Windows11 上启动报错

### ISSUE THREAD

**Issue by anysoft** [rubickCenter/rubick#137]
**描述一下这个bug**
如图，安装后快捷方式启动提示错误

**复现方式**
1. 安装应用
2. 启动应用

**预期行为**
希望能正常进入软件界面
**截图**
![image](https://user-images.githubusercontent.com/4898765/187908860-001da0c0-0af3-4b09-818a-1507ccb1295d.png)

**Comment by muwoo** [comment]
@anysoft #200 #215 v3.2.1 已修复
