### ISSUE TITLE
求代码片段生成加webdav保存，吊打utools就靠它了

### ISSUE THREAD

**Issue by woot280** [rubickCenter/rubick#138]
求代码片段生成加webdav保存，吊打utools就靠它了

**Comment by woot280** [comment]
平时用的代码要保存，到坚果云最好了

**Comment by iyjian** [comment]
保存到坚果云是啥意思，一个片段一个文件？

**Comment by muwoo** [comment]
@woot280 @iyjian 已经实现了保存到坚果云的功能 下个版本发布

**Comment by muwoo** [comment]
多端数据同步他来了!

![image](https://github.com/rubickCenter/rubick/assets/21073039/dd22f744-0a81-4bd6-8e24-97a81c2ae75e)
