### ISSUE TITLE
能手动增加本地搜索执行程序吗?

### ISSUE THREAD

**Issue by msccreater** [rubickCenter/rubick#140]
**您的功能请求是否与问题相关？ 请简单描述.**
有好多程序不是通过安装的,二是绿色软件,直接运行exe的方式, 能增加手动添加本地exe的搜索吗

**请描述一下您想要的解决方案**
, 能增加手动添加本地exe的搜索吗

**描述你考虑过的替代方案**
, 能增加手动添加本地exe的搜索吗

**Comment by linonetwo** [comment]
写一个系统插件应该能解决

**Comment by muwoo** [comment]
@msccreater 你需要的是本地启动是吧，支持了：

![image](https://github.com/rubickCenter/rubick/assets/21073039/9553acd2-9eb6-43e5-ba83-4c694a08df53)
