### ISSUE TITLE
项目拉取后在mac上跑起来没反应

### ISSUE THREAD

**Issue by LZQCN** [rubickCenter/rubick#143]
这项目用mac该咋启动，指令试了个遍，没一个能出现窗口的。
已经照着错误信息补充了缺少的依赖，不报错但就是没出现窗口。

**Comment by muwoo** [comment]
@LZQCN  项目默认不会启动任何窗口，只会在菜单栏中创建一个 `rubick logo`  菜单，`ALT + R ` 可以呼起窗口试试

**Comment by LZQCN** [comment]
搞定了，必须用 yarn ，如果用 npm 就跑了个 serve 而 electron 死活没反应
