### ISSUE TITLE
搜索插件的触发词有问题

### ISSUE THREAD

**Issue by linonetwo** [rubickCenter/rubick#153]
**描述一下这个bug**

![截屏2023-03-09 20 46 43](https://user-images.githubusercontent.com/3746270/224027164-49b09c38-1a03-4186-8aa5-8e13bd2ca99b.png)

bili 打成了淘宝

**预期行为**

应该是 bili ，而且最好能自己设定

这个没找到github仓库，不然我就PR了

**Comment by muwoo** [comment]
@linonetwo 已修复，重装一下插件，另外，插件地址在这里：https://gitee.com/rubick-center/rubick-ui-webpage-open
