### ISSUE TITLE
希望能把设置直接放在「已安装」这里

### ISSUE THREAD

**Issue by linonetwo** [rubickCenter/rubick#154]
**您的功能请求是否与问题相关？ 请简单描述.**

希望能把设置直接放在「已安装」这里，方便改。

<img width="841" alt="截屏2023-03-09 20 47 54" src="https://user-images.githubusercontent.com/3746270/224027414-22403b9d-851a-41d1-bd9e-c4b9f9a84a8f.png">

**请描述一下您想要的解决方案**

在这边新加一个，让插件作者能直接把设置页面注册到这里。

**描述你考虑过的替代方案**

或者让这边的「网页快开设置」变成一个按钮，点了之后直接添加输入到框里面，从而打开设置页面。

**Comment by layyback** [comment]
master最新的提交，这个地方的标签已经是一个按钮了，请再试试？

**Comment by linonetwo** [comment]
建议加个 nvmrc ，说明一下 node 版本，我这 node18 启动不起来 Error: error:0308010C:digital envelope routines::unsupported

这报错一般就是说 node 版本不匹配。

**Comment by linonetwo** [comment]
亲测可用，谢谢
