### ISSUE TITLE
希望网页快开能够自己新增一些网页

### ISSUE THREAD

**Issue by linonetwo** [rubickCenter/rubick#155]
**您的功能请求是否与问题相关？ 请简单描述.**

比如新增 npm 搜索

**请描述一下您想要的解决方案**

在这边加一个表单用于新增项目

**描述你考虑过的替代方案**

或者点击某个编辑按钮之后用VS code打开json配置文件，手动添加。

**Comment by linonetwo** [comment]
代码在 https://gitee.com/rubick-center/rubick-ui-webpage-open/tree/master/src  我有空改改

现在还不是很方便搜，比如搜知乎都得先打「知乎」才行

![截屏2023-03-14 19 42 22](https://user-images.githubusercontent.com/3746270/224990590-638ef026-3827-4045-977f-4aa1b7261996.png)

最好能像浏览器自带的这个，直接推荐出来了

**Comment by muwoo** [comment]
已更新新的插件：

![image](https://github.com/rubickCenter/rubick/assets/21073039/91440985-c71a-4433-bfab-f045c82f1cc0)
