### ISSUE TITLE
插件显示github地址

### ISSUE THREAD

**Issue by linonetwo** [rubickCenter/rubick#157]
**您的功能请求是否与问题相关？ 请简单描述.**

我想修改或者pr给快速搜索插件，但是找不到他的代码库在哪里。

**请描述一下您想要的解决方案**

自动把插件的npm包地址展示在插件页面里，并且允许作者填写GitHub地址，并把这地址展示出来。

**Comment by linonetwo** [comment]
最好还能拉取GitHub Discussion的内容来展示相关的评论和推荐。

**Comment by muwoo** [comment]
@linonetwo 目前插件全部存放于这个仓库：https://gitee.com/organizations/rubick-center/projects。嗯，后续确实需要放出来gitee地址
