### ISSUE TITLE
注册插件的仓库地址无法访问

### ISSUE THREAD

**Issue by linonetwo** [rubickCenter/rubick#158]
**描述一下这个bug**

https://gitee.com/monkeyWang/rubick-database/

这个现在无法访问了，建议改成用Github，可能使用一个加速地址来方便国内访问。

文档上说插件必须要在这里注册了，才会显示在可安装插件列表里。

**Comment by muwoo** [comment]
@linonetwo https://gitcode.net/rubickcenter/rubick-database 插件全部放在这里了，文档一会我改一下

**Comment by Zuoqiu-Yingyi** [comment]
> @linonetwo https://gitcode.net/rubickcenter/rubick-database 插件全部放在这里了，文档一会我改一下

文档静态资源位于 [rubickCenter/rubick at gh-pages](https://github.com/rubickCenter/rubick/tree/gh-pages) 分支, 已经一年没有更新了👀
