### ISSUE TITLE
沙拉查词，词没从 rubick 填入扩展的搜索框里

### ISSUE THREAD

**Issue by linonetwo** [rubickCenter/rubick#164]
**您的功能请求是否与问题相关？ 请简单描述.**

![截屏2023-03-10 16 58 27](https://user-images.githubusercontent.com/3746270/224271148-e5e2d054-5039-47c9-819f-15cd671e68fe.png)

**请描述一下您想要的解决方案**

我没用过正常的版本，我猜可能是之前某次更新的时候，把功能破坏了

**描述你考虑过的替代方案**

写一个从 macos dict 查词的插件，类似 https://github.com/cerebroapp/cerebro-osx-define/blob/master/src/dict.py

**Comment by muwoo** [comment]
@linonetwo 这个插件目前只支持从下面的自带搜索输入框内输入内容

**Comment by muwoo** [comment]
![image](https://user-images.githubusercontent.com/21073039/225242184-c023bb8c-379f-48da-b054-171c9cd7f5ec.png)
