### ISSUE TITLE
能可选长按中间触发吗

### ISSUE THREAD

**Issue by linonetwo** [rubickCenter/rubick#165]
**您的功能请求是否与问题相关？ 请简单描述.**

我经常长按右键，在右键菜单里选择到想用的功能后再放开。现在这个功能就会和 rubick 冲突。

还有 https://chrome.google.com/webstore/detail/ileabdhfjmgaognikmjgmhhkjffggejc 插件也需要右键拖选，也会冲突

**请描述一下您想要的解决方案**

加一个选项用于选择是使用中间长按，还是右键长按？

**描述你考虑过的替代方案**

或者干脆在按下某个快捷键（例如 rubick 启动快捷键？或者仅 alt 键？）时单击右键触发

**Comment by muwoo** [comment]
已改为 Ctrl+W触发
