### ISSUE TITLE
浏览器上复制成功但超级面板未捕获内容

### ISSUE THREAD

**Issue by linonetwo** [rubickCenter/rubick#168]
**您的功能请求是否与问题相关？ 请简单描述.**

https://user-images.githubusercontent.com/3746270/224554009-d960c36f-a241-4797-9bb0-4fd0e6d1ee27.mov

经测试，火狐和Chrome浏览器都有这个问题。

**请描述一下您想要的解决方案**

希望在任何应用上都能长按右键，让超级面板获得当前选中内容，作为输入。

**描述你考虑过的替代方案**

或者就只能使用「自动粘贴已复制内容」的功能了。但那个入口常常与「想快速查询」的需求冲突，就是想查词的时候，打开面板发现粘了一个之前很久以前复制的东西。

**Comment by linonetwo** [comment]
经测试，罗技鼠标右键就不行，但触控板右键就可以，真奇怪…

这个我有空排查一下，因为也有可能是我装的罗技鼠标的 Logic Option+ 的问题

**Comment by muwoo** [comment]
@linonetwo 好的，感谢反馈，有进展随时反馈

**Comment by muwoo** [comment]
已更改超级面板出发方式为快捷键 ctrl + w
