### ISSUE TITLE
全屏模式下不应弹出超级面板

### ISSUE THREAD

**Issue by linonetwo** [rubickCenter/rubick#169]
**您的功能请求是否与问题相关？ 请简单描述.**

在将某个应用全屏后，（不小心）长按右键会导致切换到桌面上，而且弹出的超级面板会立即消失。

https://user-images.githubusercontent.com/3746270/224554530-e8d9be27-bbe1-48a5-8fef-03415b689ecf.mov

**请描述一下您想要的解决方案**

最好能在全屏应用上直接弹出，但这不大可能，因为全屏意味着没有其他屏幕能在上面重叠。可能即使开了「always on top」也做不到。

**描述你考虑过的替代方案**

既然弹出来也会自己突然闪退关掉，那在全屏应用上就直接不要弹出得了。

或者想办法在弹出后保持打开状态。

或者从全屏应用里打开后，改为将所选内容复制到输入框里，并弹出主窗体，因为主窗体的搜索结果应该是和超级面板一样的吧？（需要让用户知道这是功能而不是bug）

**Comment by linonetwo** [comment]
纳尼，无法复现了


https://user-images.githubusercontent.com/3746270/224557460-3870c8f5-2b43-48c4-a157-f2fe4ec4ee7e.mov

**Comment by linonetwo** [comment]
再摸索一下触发方式

**Comment by muwoo** [comment]
已更改为 ctrl + w 触发方式
