### ISSUE TITLE
超级面板里的按钮点了之后没有唤起任何功能

### ISSUE THREAD

**Issue by linonetwo** [rubickCenter/rubick#170]
**描述一下这个bug**

用触控板左键点击超级面板里的按钮，超级面板会关闭，而不发生任何事情。

**复现方式**

https://user-images.githubusercontent.com/3746270/224554754-6f48d103-e8c6-4f04-8c17-1c18a22fb9cc.mov

**预期行为**

应该是会将当前选中的内容作为那个插件的输入，放到主窗口的输入框里吧？因为没有成功使用过，也不知道正确的情况应该是咋样。

**Comment by muwoo** [comment]
@linonetwo 已修复，插件卸载重新装一下
