### ISSUE TITLE
超级面板无法打开，设置页面为空白

### ISSUE THREAD

**Issue by linonetwo** [rubickCenter/rubick#171]
**描述一下这个bug**

长按右键不再弹出超级面板了

而且设置页面是空白的。

![截屏2023-03-14 19 29 28](https://user-images.githubusercontent.com/3746270/224987593-6543a903-0e60-476f-a6f9-c9e89f430c50.png)

**复现方式**
1. 下载 2.0.7
2. 删除并重新安装超级面板插件
3. 尝试右键
4. 尝试点击「超级面板设置」

**预期行为**

希望功能还像之前一样，有设置，而且可以被换出。

**Comment by muwoo** [comment]
下载插件后，mac安全与隐私需要手动添加一下rubick键盘监听和辅助功能

**Comment by muwoo** [comment]
@linonetwo 后续会逐步增加自动提示

**Comment by muwoo** [comment]
> 

然后再重启一下rubick

**Comment by linonetwo** [comment]
![截屏2023-03-15 11 27 00](https://user-images.githubusercontent.com/3746270/225198675-98c6e85f-525b-4d23-97af-1c52c3c973c6.png)
![截屏2023-03-15 11 26 50](https://user-images.githubusercontent.com/3746270/225198681-a313991c-7738-4b6d-a434-0705134d518d.png)

刚看了一下键盘监听的确已经被去掉了，我把它重新打开了，不过重新打开并重启后也还是没有生效。设置页面也还是空白的。怎么解决呢？

在开发者工具里也没有看到相关的报错和log。

**Comment by linonetwo** [comment]
rebuild robotjs,

报错

```
⠼ Building module: robotjs, Completed: 0gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/linonetwo/Desktop/repo/rubick-system-super-panel/robot/darwin/robotjs'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `gyp` failed with exit code: 1
```

 参考 https://github.com/nodejs/node-gyp/issues/2673#issuecomment-1196931379 需要加上 `--openssl_fips=''`

```
npm run rebuild-osx --openssl_fips=''
```

**Comment by linonetwo** [comment]
[robotjs.node.zip](https://github.com/rubickCenter/rubick/files/10977257/robotjs.node.zip)

产生于 robot/darwin/robotjs/bin/darwin-x64-89/robotjs.node

**Comment by linonetwo** [comment]
[osx-mouse.node.zip](https://github.com/rubickCenter/rubick/files/10977273/osx-mouse.node.zip)

产生于 robot/darwin/osx-mouse/bin/darwin-x64-89/osx-mouse.node

通过将 package.json 中的 `scripts.rebuild-osx` 内容改为 `/node_modules/.bin/electron-rebuild -m ./robot/darwin/osx-mouse --version 13.0.0` 并执行 

```
% DEBUG=electron-rebuild npm run rebuild-osx --openssl_fips=''
```

来构建

**Comment by muwoo** [comment]
@linonetwo 设置页面还没有开发，一直是个空白的，这个可以忽略。其他的问题已修复

**Comment by muwoo** [comment]
超级面板快捷简调整为 ctrl+w。不在为之前的长按右击，主要是解决不了这个问题：https://github.com/rubickCenter/rubick/issues/11
