### ISSUE TITLE
支持 macos arm64

### ISSUE THREAD

**Issue by bytemain** [rubickCenter/rubick#177]
**描述一下这个bug**

目前只有 macos x64 版本的

**Comment by 44886** [comment]
m1 的mbp，安装后点图标无任何反应

**Comment by muwoo** [comment]
@bytemain @44886 可以试一下最新的安装包

**Comment by bytemain** [comment]
<img width="783" alt="CleanShot 2023-07-03 at 11 43 16@2x" src="https://github.com/rubickCenter/rubick/assets/13938334/1251652d-5a0b-4527-b951-0cbe31828413">

还是 intel 的
