### ISSUE TITLE
能否提供从源码构建的基础方法

### ISSUE THREAD

**Issue by jackyliu16** [rubickCenter/rubick#178]
如题，目前向 linux 端提供的支持主要在于提供了 deb 包，但是能否提供从源码构建的标准操作指引，以方便在各个 linux 分发版中移植？

**Comment by MintYale** [comment]
是的 或者至少除了提供Debian系的 .deb安装包之外, 同时再提供红帽系的 .rpm安装包, 如果还有余力, 还可以提供通用 AppImage安装包. 这样一来, 基本各种主流非主流的Linux发行版都可以用上了.
