### ISSUE TITLE
Windows无法设置启动快捷键为Alt+Space

### ISSUE THREAD

**Issue by ttttmr** [rubickCenter/rubick#180]
**描述一下这个bug**
v2.2.2
默认的快捷键是Option+R，在Windows中对应Alt+R，尝试修改为Alt+Space失败

**复现方式**
1. 点击Option+R
2. 按Alt键，同时按Space

步骤2中改成其他字母按键能修改成功，只有空格不行

**预期行为**
Option+R变成Option+Space或者Alt+Space，并能通过Alt+Space启动

**截图**
按Alt+Space时出现左上角窗口
![image](https://user-images.githubusercontent.com/32825326/232233420-93357ea5-eb6d-4dad-b8ca-f522cfcd3265.png)

**Comment by beyotang** [comment]
确实，从Utools过渡过来已经习惯了，改不了这个Alt+Space

**Comment by muwoo** [comment]
@ttttmr @beyotang 是windows吗

**Comment by ttttmr** [comment]
@muwoo 是的，Windows 11
