### ISSUE TITLE
长按右键唤起不了超级面板

### ISSUE THREAD

**Issue by mzit** [rubickCenter/rubick#182]
**描述一下这个bug**
长按右键唤起不了超级面板，依旧是当前应用程序的右键菜单，用默认的快捷键ctrl+w可正常唤起

**复现方式**
macOS Ventura 13.3
设置-隐私与安全-辅助功能和输入监控都已开启
安装完超级面板后已重启

**Comment by muwoo** [comment]
长按右键在win下会和系统右击有冲突，而且获取不到选中的文件，所以改成了快捷键 **Ctrl + W** 方式呼起超级面板。需要修改的话，rubick 搜索框内搜索超级面板关键词，可以呼起设置界面，进行更改快捷键
