### ISSUE TITLE
安装插件出现错误

### ISSUE THREAD

**Issue by xiaozhanghexiaozhou** [rubickCenter/rubick#183]
![image](https://github.com/rubickCenter/rubick/assets/133929646/97ceb0a8-49c9-4d4e-b391-f33b211e7dd1)

**Comment by beyotang** [comment]
一样，请问解决了吗？

**Comment by muwoo** [comment]
@beyotang @xiaozhanghexiaozhou 目前需要安装nodejs环境，安装完后可以正常下载插件，详细的安装文档在这里：https://rubickcenter.github.io/rubick/guide/#%E5%89%8D%E8%A8%80

![image](https://github.com/rubickCenter/rubick/assets/21073039/3709f631-e1bb-4b06-bd5e-7c40c9b068e3)
