### ISSUE TITLE
如何发布插件到市场

### ISSUE THREAD

**Issue by zhk0603** [rubickCenter/rubick#189]
如题，我开发了一个插件，如何发布到市场呢？
文档：https://rubickcenter.github.io/rubick/dev/#%E5%8F%91%E5%B8%83%E6%8F%92%E4%BB%B6
里面说，PR到这个仓库：https://gitee.com/monkeyWang/rubick-database
但是这个仓库无法访问

**Comment by muwoo** [comment]
@zhk0603 是这个仓库：https://gitcode.net/rubickcenter/rubick-database  文档没更新，我修复一下

**Comment by zhk0603** [comment]
@muwoo 是的，后面也自己找到。 我PR３天了，但是没人去合并　😂

**Comment by muwoo** [comment]
@zhk0603 我去看看，欢迎加入我们的交流群，反馈会及时点
