### ISSUE TITLE
cmds type over 无效

### ISSUE THREAD

**Issue by zhk0603** [rubickCenter/rubick#191]
**描述一下这个bug**
features 的 cmds type：over 无效，比如我的插件 AICopilot 配置了许多 type是over cmd。但是我复制了一段文本或者代码。打开rubick的时候，候选的操作里面没有 我定义的。

**复现方式**
1. 安装 ai copilot
2. 复制一段代码
3. 打开rubick

**预期行为**
应该要匹配到插件配置的功能列表

**截图**

**Comment by muwoo** [comment]
@zhk0603 2.2.8 已修复
