### ISSUE TITLE
调试断点无效

### ISSUE THREAD

**Issue by sunerlin** [rubickCenter/rubick#196]
## 任何开发建议、交流学习都可以
调试时打断点灰色，且提示unbound breakpoint，想请教下该如何断点调试
![Screenshot from 2023-06-26 09-49-22](https://github.com/rubickCenter/rubick/assets/25735967/07242b2b-c72a-4f86-a787-00cb4e829215)

**Comment by muwoo** [comment]
@sunerlin 主进程的调试可以参考这篇文章：https://www.jianshu.com/p/25aff15a64ed
