### ISSUE TITLE
Rubick对于Windows11系统目前处于鸡肋状态，建议直接用PowerToys。

### ISSUE THREAD

**Issue by CongAn** [rubickCenter/rubick#198]
### 对于Rubick开发者说声抱歉，没有足够实用的插件是硬伤。

* 部分功能Windows11系统自带：历史剪切板、计算器
* 部分功能跟Windows11PowerToys重复：快速启动器、取色板、文件批量重命名、OCR……
* 部分功能都是网页，那么直接浏览器创建应用：JSON编辑器、GPT、Hoppscotch、二维码生成以及解码……
* 其他插件独立安装包应用的版本更好用。

### Windows11用户建议直接拥抱PowerToys，还可以去完善它的生态圈。

![image](https://github.com/rubickCenter/rubick/assets/16128049/4e390e9f-e5b4-4d48-9f7f-025e325e4a2b)

**Comment by du00cs** [comment]
@CongAn 你这样回复就太不地道了，首先对于Rubick以及类似工具的定位不理解，要做类比也是Alfred/Raycast以及MacOS中自带的。借用Raycast的介绍

> Inspired by the command line interface, your tools are unified as commands, and follow the same structure to make you more productive. Perform tasks in a matter of seconds.

所以如果你要的是一个一个零散的工具那你就走错地方了。这种打包的方式一定会存在不如独立工具的地方，但是只要能做到快一点点，那么就成功了。比如打开JIRA更快，打开vscode的项目更快，更快调用自己写的脚本。

开源项目喜欢可以赞助，觉得不好的就说出想要的改进方向，有能力就贡献代码，直接来踩又是什么意思呢？

**Comment by muwoo** [comment]
@CongAn 我写rubick的初衷在这里：https://hellogithub.com/article/5cda4cd5640a4cb8b364fcb5ad125cb8?url=&page=6

**Comment by q2333gh** [comment]
我觉得rubick很有价值, 特别是快捷启动这一项, 

win+s 的检索功能由windows团队实现. 难以自定义.
而rubick可以有更强大的检索和快捷启动功能.

utools最近更新有些诡异操作: 当用户从utools启动以后.一些进程会被wrap 进去.
我马上意识到这个软件可能会有不安全的风险.换用rubick以后就好了.
