### ISSUE TITLE
使用v2.2.13开发环境启动后插件市场空白

### ISSUE THREAD

**Issue by zhangxin-github** [rubickCenter/rubick#205]
## 任何开发建议、交流学习都可以
使用v2.2.13版本，开发环境分别启动了核心进程 和 插件中心，显示窗口，进入插件市场空白，切换菜单也空白：
![image](https://github.com/rubickCenter/rubick/assets/6939690/15a5b6d5-590d-4131-9890-3da3de6e9f58)
打开开发者工具：
![image](https://github.com/rubickCenter/rubick/assets/6939690/d065116d-f533-4aed-991c-afd5c8ae3bca)
![image](https://github.com/rubickCenter/rubick/assets/6939690/0d830a95-3825-4d94-adc6-bf8d88b4c869)

还请帮忙看下。

**Comment by muwoo** [comment]
@zhangxin-github 更新到最新的2.3.0版本后，然后再试试，还有问题可以扫码加我微信
