### ISSUE TITLE
两个功能及两个问题

### ISSUE THREAD

**Issue by NebulaTechs** [rubickCenter/rubick#208]
1，允许开机自启。
2，建议增加邮箱登录，另外，那个二维码能发一下吗？我这里显示不出来。
3，搜索框在屏幕中间,这样会导致展开插件商城后主窗口在屏幕偏下方的位置。
4，分离窗口后，没有最小化，最大化和关闭。

**Comment by muwoo** [comment]
1. 是有开机自启的，在 rubick 的 插件市场 -> 账户与设置 -> 基本设置 -> 通用 -> 开机启动里面进行手动开启
2. 邮箱登录目前不打算支持，如果有迫切的场景需要邮箱登录请注明，我们再考虑
3. get,下个版本处理下
4. 你是不是 dev server 启动的？dev server 启动需要手动启动 detach 目录的项目：cd detatch && npm run serve
