### ISSUE TITLE
离线安装插件

### ISSUE THREAD

**Issue by kimpvp** [rubickCenter/rubick#209]
## 交流
因为公司电脑无法安装软件，也就无法部署node.js。请问能否添加一个离线安装的方法？或者说你的插件是依赖node.js？
其实我就只要需要用到计算稿纸这个应用而已。

**Comment by muwoo** [comment]
@kimpvp 很高兴收到您的反馈，我们正在研究如何在rubick中集成nodejs环境，后续有进展第一时间通知您。

**Comment by muwoo** [comment]
@kimpvp v4.x 版本已内置 npm。
