### ISSUE TITLE
分离窗口问题

### ISSUE THREAD

**Issue by NebulaTechs** [rubickCenter/rubick#211]
**描述一下这个bug**
清楚而简洁地描述了错误是什么
#208 我没有动过任何配置，但是没有最大化，最小化和关闭按钮，只有一个开发者模式的按钮。
**复现方式**
1. 分离窗口
2. 没有最大化，最小化和关闭。

**预期行为**
清晰简明地描述了您预期的发生。
加入最大化，最小化和关闭按扭

**Comment by 6gdfg** [comment]
这应该属于feature吧

**Comment by muwoo** [comment]
@6gdfg @NebulaTechs fixed commit: https://github.com/rubickCenter/rubick/commit/676c2b9c6a5790289158c734a33ce4fb4df7fc07

**Comment by muwoo** [comment]
@6gdfg @NebulaTechs fixed commit: https://github.com/rubickCenter/rubick/commit/676c2b9c6a5790289158c734a33ce4fb4df7fc07
