### ISSUE TITLE
无法打开软件

### ISSUE THREAD

**Issue by xsrq** [rubickCenter/rubick#215]
w
![微信截图_20230802001501](https://github.com/rubickCenter/rubick/assets/116044151/60186e24-1a39-4723-8e87-1c31d0280259)
in10已经安装新版的node，还是无法打开软件

**Comment by muwoo** [comment]
@xsrq 是无法打开还是无法下载插件呢？可以加一下我微信：anjingde8744

**Comment by xsrq** [comment]
> 重新安装node.js

没用的![mmexport1690958797735.jpg](https://github.com/rubickCenter/rubick/assets/116044151/67ccf8cf-41ca-4649-aa27-32f4a7925e7a)
我也重装过，还是一个样，而且测试版node.js还没研究的明白，所以后来删除掉了旧版本也装了除测试版以外的最新版本，还是这样

**Comment by xsrq** [comment]
> 或者，使用卸载器彻底卸载Node.js,以及Rubick,之后再重装。

也彻底卸载过这俩个，连注册表都删了干净了包括安装位置文件夹都删除掉了，重新安装过解决不了，而且我看之前反馈bug也有这个问题

**Comment by muwoo** [comment]
@xsrq 试试最新版本

**Comment by xsrq** [comment]
> @xsrq 试试最新版本
![Snipaste_2023-09-13_18-05-01](https://github.com/rubickCenter/rubick/assets/116044151/f1995add-5912-473c-9b88-45e72d76cfe3)
还是不行

**Comment by jelesan** [comment]
![图片](https://github.com/rubickCenter/rubick/assets/97788570/6d53f7fb-2e52-4136-b3de-673ee0e9d30c)

**Comment by muwoo** [comment]
@xsrq @jelasin 确实有问题，已定位到问题，正在修复中

**Comment by muwoo** [comment]
@xsrq @jelasin v3.2.1 已修复，可以再安装一下试试看，有问题再开这个issue
