### ISSUE TITLE
窗口记忆

### ISSUE THREAD

**Issue by wubinstu** [rubickCenter/rubick#216]
### 1. 窗口打开位置
在 15.6 寸 1920 x 1080 屏幕上打开插件商店出现窗口下方拖底的情况, 手动调整窗口位置后下次打开窗口位置会自动恢复, 这为操作带来很大不便, 如果能优化一下可以记忆窗口上次打开位置就好了
### 2. 插件商店复位
根据当前版本(2.4.1)的客观表现, 当用户打开插件商店并使用鼠标点击其它地方使得窗口消失后, 无论是1分钟, 10分钟后快捷键呼出窗口依然保持着商店的打开状态, 然而事实上是只有在短时间内重新打开窗口才有可能是继续使用插件商店, 而稍微长的一段时间后大概率是为了搜索. 所以可以设置一个时间阈值, 超时就将窗口状态还原

**Comment by muwoo** [comment]
`在 15.6 寸 1920 x 1080 屏幕上打开插件商店出现窗口下方拖底的情况`

@wubinstu 能否提供一下当前现状的截图

**Comment by wubinstu** [comment]
> `在 15.6 寸 1920 x 1080 屏幕上打开插件商店出现窗口下方拖底的情况`
> 
> @wubinstu 能否提供一下当前现状的截图

@muwoo 录制了一段gif, 希望能正常播放
![动画](https://github.com/rubickCenter/rubick/assets/63046636/cfe7f1e6-46cd-4d3b-91ed-8a3bd496deeb)

**Comment by muwoo** [comment]
@wubinstu 
问题1 已支持
问题2 还没有计划支持，目前这个feature感觉还不是很通用
