### ISSUE TITLE
安装插件速度太慢，有什么办法吗？

### ISSUE THREAD

**Issue by laniv** [rubickCenter/rubick#219]
## 任何开发建议、交流学习都可以
不管是开魔法，还是不开，速度都慢。
有些能安装，有些一直 转，安装不了。
还有，插件数量太少了，希望更多高手加入添加插件。

**Comment by muwoo** [comment]
@laniv 找到账户与设置 -> 内网部署 然后点一下恢复设置后保存，再重启一下rubick 即可

![image](https://github.com/rubickCenter/rubick/assets/21073039/2152295e-4072-4b0c-90ec-4e50c42bc41e)

**Comment by great-man2096** [comment]
> @laniv 找到账户与设置 -> 内网部署 然后点一下恢复设置后保存，再重启一下rubick 即可
> 
> ![image](https://user-images.githubusercontent.com/21073039/265301279-2152295e-4072-4b0c-90ec-4e50c42bc41e.png)

试了，没什么效果，还是一直在转圈

**Comment by muwoo** [comment]
帮忙截一下你配置这里的图

**Comment by great-man2096** [comment]
> 帮忙截一下你配置这里的图

![image](https://github.com/rubickCenter/rubick/assets/80567513/46a141d3-9e73-4ec1-9cd3-6000275d059a)

**Comment by laniv** [comment]
> @laniv 找到账户与设置 -> 内网部署 然后点一下恢复设置后保存，再重启一下rubick 即可
> 
> ![image](https://user-images.githubusercontent.com/21073039/265301279-2152295e-4072-4b0c-90ec-4e50c42bc41e.png)

谢谢，确实可以了。很快了！
还有个问题，超级面板 可以改成 鼠标中键 来唤醒吗？

**Comment by muwoo** [comment]
@laniv 超级面板完善功能还在开发中

**Comment by muwoo** [comment]
@great-man2096 windows 吗？帮忙打开一下开发者工具，然后安装看看有没有报错，如果有报错的话，帮忙截图一下。也可以加一下我的微信 `anjingde8744` 这样方便沟通
