### ISSUE TITLE
更新3.0后，打开插件都是空白的？

### ISSUE THREAD

**Issue by laniv** [rubickCenter/rubick#220]
![QQ截图20230904120357](https://github.com/rubickCenter/rubick/assets/15064212/8a90cd52-faa2-4723-8dc3-6b22f789615d)
![QQ截图20230904120518](https://github.com/rubickCenter/rubick/assets/15064212/2aebe47b-1324-4c15-b552-016f0169a741)
![QQ截图20230904120536](https://github.com/rubickCenter/rubick/assets/15064212/41c13511-2cbd-4ac8-a906-ec0cbd2d4918)

还有，超级面板也设置不了，想改成 鼠标中键 换出，Ctrl+w 不太方便。

**Comment by muwoo** [comment]
@laniv 3.0 和历史版本不兼容，所有的插件都需要卸载重装了
