### ISSUE TITLE
全局快捷键不生效

### ISSUE THREAD

**Issue by hityb** [rubickCenter/rubick#221]
## 全局快捷键不生效
![image](https://github.com/rubickCenter/rubick/assets/58910855/b4cf66e4-43e8-4b6f-b779-430ab9776909)

windows10系统
rubick3.0
设置了两个全局快捷键都无法生效，已经排查快捷键没有冲突。
希望哪位大佬看看是哪里的问题。

**Comment by muwoo** [comment]
@hityb 更新到 3.0.1 再试试
