### ISSUE TITLE
建议改一个名字，这个名字不好理解，名字很重要

### ISSUE THREAD

**Issue by ydaydayup** [rubickCenter/rubick#223]
## 任何开发建议、交流学习都可以
比如notepad++   , notepad--

utools  --- wtools

**Comment by cc01cc** [comment]
关于取名来源可以参考作者的这篇文章：https://hellogithub.com/article/5cda4cd5640a4cb8b364fcb5ad125cb8?url=&page=6

> 开篇第一步，按照我之前的套路都是先取好名字先占个坑。我是个 Dota 玩家，之前写了一本《从0开始可视化搭建》的小册，里面使用了 Dota 中一个英雄的名字 coco（船长）。这次我取名的是 rubick 即 拉比克。Rubick(拉比克) 也是 Dota 里面的英雄之一，其核心技能是插件化使用其他英雄的技能，用完即走。非常符合本工具的设计理念，所以取名 Rubick。

知道名字来源，也就不觉得不好理解了。我个人欣赏这种取名方式，并且尊重作者的选择。

**Comment by cc01cc** [comment]
作为开源项目，没有商业上那种见名知意的迫切需求，并且开源项目，相对会更多的包含作者，社区贡献者的感情，期待等，就像自己的孩子一样，我个人也觉得这个名字并无不妥。

再者没必要跟着别人取名。

**Comment by muwoo** [comment]
@ydaydayup 现在改起来比较麻烦，很多地方都是用了rubick 关键字。暂时不改了吧

**Comment by cidosx** [comment]
拉比克总是在伺机窃取全新的法术，以彼之道还施彼身。
