### ISSUE TITLE
下载插件报错

### ISSUE THREAD

**Issue by Allen-zhang1990** [rubickCenter/rubick#227]
**描述一下这个bug**
在插件市场下载插件的时候报错：A JavaScript error occurred in the main process

**截图**

![58f78e8779fdc6207c9ac15f4b442e0](https://github.com/rubickCenter/rubick/assets/20653843/e311727f-c55b-4615-9ff6-6207c46093be)

**Comment by muwoo** [comment]
@Allen-zhang1990 需要安装nodejs环境，文档在这里：https://rubickcenter.github.io/rubick/guide/#%E5%89%8D%E8%A8%80
