### ISSUE TITLE
官网https://rubick.vip/ 点击下载->windows下载 下载一个exe.htm

### ISSUE THREAD

**Issue by RuiZhang-cn** [rubickCenter/rubick#229]
**描述一下这个bug**
官网https://rubick.vip/ 点击下载->windows下载 下载一个exe.htm
**复现方式**
1. 访问https://rubick.vip/ 
2. Click on '下载->windows下载'
我这边的下载链接是https://rubick.vip/api/download/exe

**预期行为**
清晰简明地描述了您预期的发生。

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。

**Comment by mayishan1** [comment]
可以在这里下载

https://github.com/rubickCenter/rubick/releases/tag/v3.0.1

**Comment by muwoo** [comment]
@RuiZhang-cn 已修复，这个下载链接还是指向了github的releases 上，所以可能有点慢，如果太慢了，可以尝试使用代理下载：https://ghproxy.com/
