### ISSUE TITLE
官网mac版本无法下载

### ISSUE THREAD

**Issue by tong822218** [rubickCenter/rubick#233]
**描述一下这个bug**
官网上mac版本下载提示找不到资源

**复现方式**
1.打开官网
2.点击右上角下载rubick ,选择mac
**预期行为**
正常下载。

**截图**
<img width="487" alt="image" src="https://github.com/rubickCenter/rubick/assets/9926531/35648071-6702-4027-849a-af64639733e2">

**Comment by mayishan1** [comment]
可以在这里下载

https://github.com/rubickCenter/rubick/releases/tag/v3.0.1

**Comment by muwoo** [comment]
@tong822218 已修复，这个下载链接还是指向了github的releases 上，所以可能有点慢，如果太慢了，可以尝试使用代理下载：https://ghproxy.com/
