### ISSUE TITLE
希望可以自定义包管理器

### ISSUE THREAD

**Issue by yuyuko233** [rubickCenter/rubick#239]
希望可以自定义包管理器, 比如支持 pnpm yarn 等, 这样有全局缓存的包就不用再安装一遍了

**Comment by yuyuko233** [comment]
> @yuyuko233 现在使用的 cnpm 的源，理论上应该是秒装，切换源感觉意义不是很大呀

比如使用 pnpm 的话有些包安装过会缓存在硬盘里, pnpm 会直接 link 过去, 不用再安装一遍了, 减少硬盘重复写入和占用

**Comment by muwoo** [comment]
@yuyuko233 已内置包管理器，无需自定义了
