### ISSUE TITLE
项目运行不了

### ISSUE THREAD

**Issue by liangshaojie** [rubickCenter/rubick#240]
## 任何开发建议、交流学习都可以
(node:38712) [DEP0128] DeprecationWarning: Invalid 'main' field in 'D:\github\rubick\dist_electron\package.json' of 'background.js'. Please either fix that or report it to the module author
(Use `electron --trace-deprecation ...` to show where the warning was created

在执行npm run electron:serve的时候报错了

➜  rubick node -v
v16.20.0
➜  rubick git:(v3.1.1) ✗ npm -v
8.19.4
➜  rubick git:(v3.1.1) ✗

以上是我的node版本

**Comment by muwoo** [comment]
@liangshaojie windows 还是mac？项目建议使用yarn进行安装，先删掉 node_modules 再用yarn 安装试试看。另外项目依赖 node-gyp 环境，请确保电脑上已安装好了 node-gyp 环境

**Comment by liangshaojie** [comment]
@muwoo 好的，使用yarn    可以运行成功了，谢谢
