### ISSUE TITLE
安装插件时候报错

### ISSUE THREAD

**Issue by KleinPan** [rubickCenter/rubick#241]
![Dingtalk_20230921153627](https://github.com/rubickCenter/rubick/assets/34428802/fd10e02b-548c-45ac-b562-37c20634aa21)

报错截图如上图所示
怀疑可能和公司的加密系统之类的有关系，如果是这个问题的话可以忽略；

**Comment by muwoo** [comment]
@KleinPan 你应该没有安装nodejs环境吧

**Comment by muwoo** [comment]
@KleinPan windows 下安装nodejs环境的稳定说明：https://rubickcenter.github.io/rubick/guide/#%E5%89%8D%E8%A8%80

**Comment by KleinPan** [comment]
确实好了，建议把这个写的醒目一点😄
