### ISSUE TITLE
安装任何插件都会报错（见截图）

### ISSUE THREAD

**Issue by grimseraph** [rubickCenter/rubick#251]
![屏幕截图 2023-09-28 110853](https://github.com/rubickCenter/rubick/assets/4180811/1b9c2b31-9875-42b3-93e3-68f268fef8a8)

重启无效

**Comment by muwoo** [comment]
@grimseraph  目前rubick依赖npm进行插件安装，需要用户本地有node环境，win下安装node环境文档：https://juejin.cn/post/6892790243687137287 rubick 正在内部集成node环境，后续将会修复这个问题

**Comment by muwoo** [comment]
rubick v4.1.0-beta.2 版本后，不再依赖本地node环境，可以不安装npm直接下载插件啦！

![image](https://github.com/rubickCenter/rubick/assets/21073039/9f6fe8f8-ef04-48c3-9498-a07d6aad245f)
