### ISSUE TITLE
pouchDB 不是一个好用的数据库

### ISSUE THREAD

**Issue by code-lixm** [rubickCenter/rubick#254]
## 任何开发建议、交流学习都可以

pouchDB 不是一个好用的数据库，他因为管理的数据版本的问题，导致他的检索极慢，可以换成别的简易数据库

**Comment by muwoo** [comment]
@code-lixm 因为社区很多开源的插件都是基于 pouchdb 来做的，使用 pouchdb 的主要原因是为了兼容社区插件
