### ISSUE TITLE
搜索tg打开后直接卡死，操作不了了。

### ISSUE THREAD

**Issue by zkname** [rubickCenter/rubick#255]
**描述一下这个bug**
搜索tg打开后直接卡死，操作不了了。系统win11，nodejs v18.17.1

**复现方式**

**预期行为**
搜索tg打开后直接卡死，操作不了了，删除输入都不行，整个程序卡死了，只能快捷键显示隐藏
**截图**
![image](https://github.com/rubickCenter/rubick/assets/31124863/f74bb795-4966-4892-84ef-672106fc3acd)

**Comment by 1129921824** [comment]
tag

**Comment by muwoo** [comment]
@zkname 感谢反馈，有几个问题麻烦操作一下：
1. 试试打开其他app会不会卡死？
2. 试试打开插件会不会卡死？

**Comment by muwoo** [comment]
@zkname 已修复，v4.0.3
