### ISSUE TITLE
在插件分离窗口且未关闭的情况下，再次打开该插件并分离窗口会导致Rubick搜索框卡死

### ISSUE THREAD

**Issue by BlueBrightWind** [rubickCenter/rubick#263]
**描述一下这个bug**
在插件分离窗口且未关闭的情况下，再次打开该插件并分离窗口，会发现第一个插件变为空白，无法关闭。强行关闭会导致Rubick搜索框卡死，不能拖动搜索框，也不能输入内容，需要重启rubick才能正常使用

**复现方式**
1. 打开一个插件，这里以剪贴板为例
2. 将剪贴板插件分离窗口
3. 通过ALT+R打开Rubick搜索框，再次进入剪贴板插件
4. 此时发现分离窗口的插件变为空白，新打开的剪贴板插件正常
5. 对新打开的剪贴板插件分离窗口，会发现第一次打开的插件窗口卡死，无法关闭，此时触发bug
6. 若强行关闭第一次打开的剪贴板，会导致Rubick搜索框卡死

**预期行为**
如上述方式可以稳定触发bug，隔壁某个软件的解决方式是打开相同的插件会立刻关闭上一个插件的窗口。

**截图**
正常的窗口
![image](https://github.com/rubickCenter/rubick/assets/86959294/7dbd4a31-1584-4f38-8e55-4d3caa240516)
触发bug的窗口
![image](https://github.com/rubickCenter/rubick/assets/86959294/b613cf96-6559-4845-8d0e-328072deca9a)
两个窗口
![image](https://github.com/rubickCenter/rubick/assets/86959294/923bf17a-0385-41a3-96a1-c307ab801eea)
此时第一个窗口已无法关闭

**Comment by muwoo** [comment]
@BlueBrightWind 麻烦提供一下 rubick 版本信息和你的操作系统

**Comment by BlueBrightWind** [comment]
Windows 11 专业版 22H2 22621.2428，rubick版本 4.0.4 x64

**Comment by BlueBrightWind** [comment]
> @BlueBrightWind 麻烦提供一下 rubick 版本信息和你的操作系统
Windows 11 专业版 22H2 22621.2428，rubick版本 4.0.4 x64
