### ISSUE TITLE
分离窗口关闭后再次点击插件市场搜索框失去响应

### ISSUE THREAD

**Issue by geticsen** [rubickCenter/rubick#264]
**描述一下这个bug**
分离窗口关闭后再次点击插件市场搜索框失去响应

**复现方式**
1.点击插件市场（可以随意选择一个插件）并分离窗口，然后关掉分离后的窗口
2.再次唤起Rubick搜索框
3.点击插件市场后搜索框失去响应

**预期行为**
关闭分离窗口后可再次打开插件市场

**截图**

**Comment by muwoo** [comment]
@geticsen v4.0.5已修复
