### ISSUE TITLE
使用快捷键呼出功能后，功能固定在rubick搜索框，后面在使用快捷键不能呼出功能

### ISSUE THREAD

**Issue by juneren26** [rubickCenter/rubick#268]
**描述一下这个bug**
通过快捷键呼出rubick功能插件后，功能插件固定在rubick搜索框，再次使用快捷键无法将呼出功能，需要使用Alt+R呼出，或者清空所有框功能插件名，再次使用功能插件快捷键才能呼出

**复现方式**
1.下载插件系统剪切板
2. 全局设置中绑定快捷键Alt+Q为剪切板的呼出快捷键
3. 通过Alt+Q呼出剪切板后，剪切板常驻在搜索框
4. 再次按下Alt+Q发现无任何效果，不能呼出剪切板
5. 按下Alt+R呼出rubick，正常显示剪切板
6. 删除搜索框中的剪切板后，再次按下Alt+Q又可以呼出剪切板

**预期行为**
不管历史是否通过快捷键调用过某个功能插件，功能插件是否固定在搜索框中，通过快捷键均可呼出对应的功能插件

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。
![image](https://github.com/rubickCenter/rubick/assets/70616792/36d993c3-7cbd-4114-a394-02fccae37dc0)
![image](https://github.com/rubickCenter/rubick/assets/70616792/1d4ecb8c-244b-44fb-938f-0b6c22ad22b1)
![image](https://github.com/rubickCenter/rubick/assets/70616792/f839ccf6-7f78-41e9-8954-726e6567861c)

**Comment by juneren26** [comment]
操作系统版本号Windows 10 企业版 LTSC 21H2
Rubick版本4.0.5

**Comment by muwoo** [comment]
@juneren26 v4.0.6版本以上已修复
