### ISSUE TITLE
mac打开显示已损坏

### ISSUE THREAD

**Issue by kingshuaishuai** [rubickCenter/rubick#269]
**描述一下这个bug**
mac显示已损坏，安装后无法打开。已尝试多次。芯片 Apple M1 Pro，系统版本：13.5.2 (22G91
**复现方式**
安装后直接打开，或安装后 访达 -> 应用程序 -> 右键打开，两种方式均不行

**预期行为**
能正常打开

**Comment by muwoo** [comment]
@kingshuaishuai 解决方案： https://github.com/rubickCenter/rubick/issues/247
