### ISSUE TITLE
多个插件分离窗口后关闭其中一个分离窗口，其它分离窗口无法关闭

### ISSUE THREAD

**Issue by geticsen** [rubickCenter/rubick#270]
**描述一下这个bug**
超过两个插件分离窗口后关闭其中一个分离窗口，其它分离窗口无法关闭

**复现方式**
1.打开超过两个插件并分离窗口
2.关闭其中一个分离窗口的插件（有可能出现关闭窗口不对应的情况）
3.其它分离窗口无法关闭

**预期行为**
合理关闭分离窗口

**截图**

**Comment by muwoo** [comment]
@geticsen 什么版本的rubick?

**Comment by geticsen** [comment]
win11，4.0.8
<img width="283" alt="image" src="https://github.com/rubickCenter/rubick/assets/41274495/bd335fdb-4d8b-4441-96e9-0ea3a07e39f5">

**Comment by muwoo** [comment]
@geticsen 4.0.9 已修复

**Comment by geticsen** [comment]
可以~
