### ISSUE TITLE
安装插件的时候报错

### ISSUE THREAD

**Issue by ygxiuming** [rubickCenter/rubick#272]
![image](https://github.com/rubickCenter/rubick/assets/54978922/0fbfa4e8-3a1b-4851-ac87-3ae5b8e853a9)

**Comment by ygxiuming** [comment]
重启卡空白
![image](https://github.com/rubickCenter/rubick/assets/54978922/40b97273-052a-45d4-b4a2-4cf3510baa4c)
![image](https://github.com/rubickCenter/rubick/assets/54978922/73656d86-f218-4214-9a82-2a584c771e25)

**Comment by muwoo** [comment]
@ygxiuming 插件是依赖于npm进行安装的，需要本地提前安装node环境：https://github.com/rubickCenter/rubick/issues/251
