### ISSUE TITLE
设置内容保存不了

### ISSUE THREAD

**Issue by Yang-Kyle** [rubickCenter/rubick#274]
**描述一下这个bug**
- 设置内容，一会就失效（恢复原始设置）
- 重启会丢掉一部分数据，并且设置内容都重置到初始

**复现方式**
1. 按下<kbd>Ctrl+Space</kbd>
2. 点底部按钮 → 账户和设置 → 进行一些设置
3. 任务栏图标右键 → 重启
4. 数据丢失，设置也回到刚下载时

**预期行为**
> 正常保存数据

**截图**

**Comment by muwoo** [comment]
@Yang-Kyle 
辛苦提供一下rubick 版本

**Comment by Yang-Kyle** [comment]
@muwoo 
> Win 10 21H2

![图片](https://github.com/rubickCenter/rubick/assets/79508698/898fb7a4-8109-4677-a5a1-48909b44297e)

**Comment by muwoo** [comment]
@Yang-Kyle 试试以下操作能否恢复：
1. 打开插件市场
2. 点击右侧的... 打开开发者工具
3. 在控制台输入 `window.rubick.db.remove('rubick-local-config')` 回车
4. 重启 rubick
5. 再试试看数据能否正常保存

**Comment by Yang-Kyle** [comment]
> 感谢及时详细的说明 @muwoo

重启后又丢了一次，然后再重启，测试一下午目前没有问题.
webDAV 也变稳定和快速了. 先正常使用观望一段时间
