### ISSUE TITLE
内网安装以后超级面板插件安装不了

### ISSUE THREAD

**Issue by bestv5** [rubickCenter/rubick#275]
**描述一下这个bug**
内网安装软件，内网部署配置也填写了。其他插件可以安装，但是超级面板插件下载失败。

**复现方式**
内网（不能联网）安装  - 配置内网部署  - 插件市场里点击超级面板超级下载图标。

**预期行为**
超级面板能够下载并安装。

**截图**

**Comment by muwoo** [comment]
@bestv5 临时解决方案：先切到 taobao 的npm 源： https://registry.npmmirror.com，下载完超级面板插件后，再切到你的内网npm源

**Comment by bestv5** [comment]
> @bestv5 临时解决方案：先切到 taobao 的npm 源： `https://registry.npmmirror.com`，下载完超级面板插件后，再切到你的内网npm源

我理解本身内网电脑不能连接taobao源，我切到淘宝源也不行吧？


另一种思路：我把公司的npm镜像加上taobao源，是不是也可以？或者说我在能联网的机器上，把超级面板插件下载下来，然后放到本地安装一下？

**Comment by bestv5** [comment]
我在mac上安装了超级面板，打开rubick报错了。
Uncaught Exception:
TypeError: Object has been destroyed
at click (/Applications/rubick.app/Contents/Resources/app.asar/background.js:2:1554320)
at MenuItem.click (node:electron/js2c/browser_init:2:30958)
at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)

**Comment by muwoo** [comment]
> > @bestv5 临时解决方案：先切到 taobao 的npm 源： `https://registry.npmmirror.com`，下载完超级面板插件后，再切到你的内网npm源
> 
> 我理解本身内网电脑不能连接taobao源，我切到淘宝源也不行吧？
> 
> 另一种思路：我把公司的npm镜像加上taobao源，是不是也可以？或者说我在能联网的机器上，把超级面板插件下载下来，然后放到本地安装一下？

是这个道理

**Comment by muwoo** [comment]
> 我在mac上安装了超级面板，打开rubick报错了。 Uncaught Exception: TypeError: Object has been destroyed at click (/Applications/rubick.app/Contents/Resources/app.asar/background.js:2:1554320) at MenuItem.click (node:electron/js2c/browser_init:2:30958) at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)

提供一下rubick版本

**Comment by bestv5** [comment]
> > 我在mac上安装了超级面板，打开rubick报错了。 Uncaught Exception: TypeError: Object has been destroyed at click (/Applications/rubick.app/Contents/Resources/app.asar/background.js:2:1554320) at MenuItem.click (node:electron/js2c/browser_init:2:30958) at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)
> 
> 提供一下rubick版本

4.0.3.  我是这么操作的，在本地命令行执行npm -g install rubick-superx ，然后打开rubick就报错了。
然后我又卸载了，再打开就好了。

**Comment by muwoo** [comment]
> > > 我在mac上安装了超级面板，打开rubick报错了。 Uncaught Exception: TypeError: Object has been destroyed at click (/Applications/rubick.app/Contents/Resources/app.asar/background.js:2:1554320) at MenuItem.click (node:electron/js2c/browser_init:2:30958) at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)
> > 
> > 
> > 提供一下rubick版本
> 
> 4.0.3. 我是这么操作的，在本地命令行执行npm -g install rubick-superx ，然后打开rubick就报错了。 然后我又卸载了，再打开就好了。 忽略这个问题吧....

是这样的，rubick 插件安装的路径在 `/Users/${你的用户名}/Library/Application Support/rubick/rubick-plugins/node_modules` 下 所以 你需要指定 rubick-superx 的安装目录：

```shell
$ npm install --prefix /Users/${你的用户名}/Library/Application Support/rubick/rubick-plugins --registery https://registry.npmmirror.com/
```

**Comment by muwoo** [comment]
> > > 我在mac上安装了超级面板，打开rubick报错了。 Uncaught Exception: TypeError: Object has been destroyed at click (/Applications/rubick.app/Contents/Resources/app.asar/background.js:2:1554320) at MenuItem.click (node:electron/js2c/browser_init:2:30958) at Menu._executeCommand (node:electron/js2c/browser_init:2:36354)
> > 
> > 
> > 提供一下rubick版本
> 
> 4.0.3. 我是这么操作的，在本地命令行执行npm -g install rubick-superx ，然后打开rubick就报错了。 然后我又卸载了，再打开就好了。 忽略这个问题吧....

这样安装有问题，因为rubick 执行 npm install 插件之后，还会写入一份配置文件，告诉 rubick 主程序当前已安装了改程序，才可以读取和使用插件，所以必须通过rubick 自身的安装来实现插件的安装。

另外，rubick 所有插件都需要安装到 `/Users/${你的用户名}/Library/Application Support/rubick/rubick-plugins/node_modules` 这个目录下
