### ISSUE TITLE
M2Pro MacOS 14.1 arm64版本无法安装

### ISSUE THREAD

**Issue by guowenfh** [rubickCenter/rubick#282]
**描述一下这个bug**
尝试安装了 rubick-4.1.2-arm64、rubick-4.1.1-arm64 rubick-4.0.10-arm64，都无法安装直接程序错误，见下图。
使用 rubick-4.1.2-x64.dmg 正常安装，可使用

**复现方式**
M2 Pro 下载->打开->拖拽-> 打开 rubick -> 显示已损坏

**预期行为**
M1+系列正常安装

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。
![image](https://github.com/rubickCenter/rubick/assets/15883471/982c7504-b913-4701-a951-d27f8fcec186)

**Comment by muwoo** [comment]
@guowenfh 这里 https://github.com/rubickCenter/rubick/issues/247
