### ISSUE TITLE
mac m2 14.0无法使用

### ISSUE THREAD

**Issue by fsy0718** [rubickCenter/rubick#283]
**描述一下这个bug**
下载[MacOS M1 下载](https://rubick.vip/api/download/arm64.dmg)后打开提示ribick已损坏，无法打开

**复现方式**
1. 下载[MacOS M1 下载](https://rubick.vip/api/download/arm64.dmg)
2. 点开移动到applications
3. 启动台打开rubick
4. 提示已损坏

**预期行为**
正常打开

**截图**
<img width="1456" alt="企业微信截图_ac89c99f-662f-4e5f-b0bb-3a1f2f51cde2" src="https://github.com/rubickCenter/rubick/assets/3926479/5097e3d2-821d-4628-a198-d50006af36ac">

**Comment by muwoo** [comment]
@fsy0718 #247
