### ISSUE TITLE
mac m1下载安装完成后打开程序报错

### ISSUE THREAD

**Issue by YCenhao** [rubickCenter/rubick#285]
**描述一下这个bug**
清楚而简洁地描述了错误是什么

**复现方式**

**预期行为**
清晰简明地描述了您预期的发生。

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。

**Comment by YCenhao** [comment]
<img width="260" alt="image" src="https://github.com/rubickCenter/rubick/assets/83417580/3b95ef23-7b9c-4f16-9d45-d65d18ccca5c">

**Comment by YCenhao** [comment]
最近两个版本均报错
<img width="786" alt="image" src="https://github.com/rubickCenter/rubick/assets/83417580/cbf42560-51bf-4d0e-9b69-86c1f6e7cdda">

**Comment by ceu** [comment]
M1, Mac mini, 同样的问题，打开就报错，Ribick 已损坏!

**Comment by ceu** [comment]
已修复，下面是解决方案，请关闭该问题!
https://github.com/rubickCenter/rubick/issues/247#issuecomment-1737007607
