### ISSUE TITLE
API中是否能够加入判断系统类型的api，和系统剪贴板功能。

### ISSUE THREAD

**Issue by trifolium-wang** [rubickCenter/rubick#286]
**您的功能请求是否与问题相关？ 请简单描述.**
API中是否能够加入判断系统类型的api，和系统剪贴板功能。

**请描述一下您想要的解决方案**
相对utools缺少的api太多了，迁移变成了大难题。

**描述你考虑过的替代方案**
添加完善的api

**Comment by muwoo** [comment]
@trifolium-wang 其实不少的，文档中api我没罗列全，基本上都涵盖了，支持的 所有 api可以参考这里：https://github.com/rubickCenter/rubick/blob/master/public/preload.js

**Comment by muwoo** [comment]
@trifolium-wang 如果还有需要但是缺少的，可以补充，我们会尽快实现

**Comment by trifolium-wang** [comment]
好的，我有时间迁移一下试试。

**Comment by trifolium-wang** [comment]
有无群组我加一个，可以问问题的，打开文档中的很多操作跟操作完全不一致，想了解一下。

**Comment by muwoo** [comment]
加我微信，我拉你：anjingde8744
