### ISSUE TITLE
输入命令后功能列表排序

### ISSUE THREAD

**Issue by rebron1900** [rubickCenter/rubick#287]
**您的功能请求是否与问题相关？ 请简单描述.**
1. 使用完某个插件后会在rubick的初始窗口固定一个磁贴，但是重启rubick后会消失？
2. 目前输入命令后出现的插件列表排序是固定的，使用起来不太方便。

**请描述一下您想要的解决方案**
1.1. 这个可以保留吗？
1.2. 可以保留一定数量，是不是可以考虑增加一个选项设置展示多少个磁贴
1.3. 用户可以钉住一些插件在这个初始界面。

2.1. 可以根据使用频次排序
2.2. 可以根据命令类型预估用户需要使用的插件
2.3. 可以钉住一些常用插件在顶部

**描述你考虑过的替代方案**
无

**Comment by muwoo** [comment]
很好的建议！实现中

**Comment by muwoo** [comment]
@rebron1900 v4.1.5已实现
