### ISSUE TITLE
输入关键字、选择文件搜索后不能立刻出现搜索结果

### ISSUE THREAD

**Issue by rebron1900** [rubickCenter/rubick#290]
**描述一下这个bug**
输入要搜索的文件关键字后，在出现的插件列表中选择「文件搜索」，之后会跳转到文件所搜插件，并自动填入搜索关键字。
但是不会出现搜索结果，需要手动删除关键字之后重新输入才可以出现结果。

**预期行为**
正常情况跳转到搜索插件后应该立即显示匹配的文件。

**截图**
![image](https://github.com/rubickCenter/rubick/assets/7929884/034cd86b-4f39-4af5-b203-8bc8d77596b1)

**Comment by rebron1900** [comment]
测试了一下，这个问题好像还是没有修复

**Comment by muwoo** [comment]
@rebron1900 4.1.6 修复类了
