### ISSUE TITLE
剪贴板插件提示权限问题

### ISSUE THREAD

**Issue by rebron1900** [rubickCenter/rubick#294]
**描述一下这个bug**
新电脑安装rubick并从云端同步了数据到本地，然后剪贴板插件提示如下图，根据提示发现目标路径没有该文件夹
![67706a2fa5076febcedb8143544157c](https://github.com/rubickCenter/rubick/assets/7929884/3f5ccc85-1c1c-4c62-97b4-df0bf4ab4a20)

**复现方式**

**预期行为**

**截图**

**Comment by 1129921824** [comment]
系统插件安装完需要重启rubick，后期可能会增加提示，解决请关闭issue

**Comment by rebron1900** [comment]
已解决
