### ISSUE TITLE
【建议】打包增加对asar单独出包的支持

### ISSUE THREAD

**Issue by bestv5** [rubickCenter/rubick#300]
### 使用场景
软件的使用场景完全在内网中，每次更新都需要下载更新包后通过邮件传输到内网计算机。但是邮件对附件大小又有要求，每次需要拆分多个压缩包后传输，非常不方便。

最近使用obsidian笔记软件，看到它打包中有asar单独出包的方式，才几兆，感觉挺方便。
![image](https://github.com/rubickCenter/rubick/assets/15650275/d5e70150-7140-4657-8b3c-cfc59688da1b)

希望作者也能够支持对asar单独出包，只需要替换改部分文件就能完成更软件更新。

**Comment by muwoo** [comment]
@bestv5 有点没搞明白，为啥安装包要通过邮件传输到内网计算机，而不是直接通过github下载呢？

**Comment by bestv5** [comment]
> @bestv5 有点没搞明白，为啥安装包要通过邮件传输到内网计算机，而不是直接通过github下载呢？

内网计算机，无法访问互联网，只能在内部局域网工作和收发邮件.

**Comment by muwoo** [comment]
@bestv5 微信at我一下，帮我测试一下

**Comment by muwoo** [comment]
已支持，v4.1.6后的版本更新发布，release 中将会多一个 `app.asar.gz` 文件
