### ISSUE TITLE
开发环境无法搭建，能否整理一下包依赖，把过期的，无效的包删除或更新

### ISSUE THREAD

**Issue by AnliC24** [rubickCenter/rubick#301]
![image](https://github.com/rubickCenter/rubick/assets/39631590/37819156-8e5d-4f12-81f7-893e69d767ae)

![image](https://github.com/rubickCenter/rubick/assets/39631590/a22a5387-f437-4e0d-a777-2c6aa10a4e1f)

![image](https://github.com/rubickCenter/rubick/assets/39631590/8aff4e14-9021-43aa-a7cb-c7e1ec9db548)

![image](https://github.com/rubickCenter/rubick/assets/39631590/c640d17c-703c-4e9f-a0ca-09c430581fb0)

dns 这个包几乎无法下载，提示切换 node 0.8.x 的版本，这个版本根本无法使用。使用 node  v14 的版本， electron 又需要  node v16 的版本，这是个循环依赖，请解决一下

**Comment by muwoo** [comment]
@AnliC24 启动是 npm run electron:serve 不是 npm run serve

**Comment by muwoo** [comment]
node v16 就可以了，用 electron:serve 启动不会有dns这个错
