### ISSUE TITLE
剪贴板插件里的图片不能复制

### ISSUE THREAD

**Issue by rebron1900** [rubickCenter/rubick#302]
**描述一下这个bug**
剪贴板插件里的图片不能复制，其他文字内容没有问题。

**复现方式**
1. 截图
2. 打开剪贴板插件，列表中会出现图片内容
3. 选中图片内容，点击复制
4. 去其他地方粘贴会发现图片压根没有被复制。

**预期行为**
Ctrl+C或者点击复制按钮后图片应该会存入系统剪贴板，可以在其他地方粘贴。

**截图**

![Uploading 1.gif…]()

**Comment by rebron1900** [comment]
![1](https://github.com/rubickCenter/rubick/assets/7929884/c8cee9b6-6a65-4306-b021-b001f7240d55)

**Comment by rebron1900** [comment]
![1](https://github.com/rubickCenter/rubick/assets/7929884/8705955e-e0e5-4f9a-9ebe-b5e1e9351891)

**Comment by muwoo** [comment]
@rebron1900 已修复，通过输入框搜索Clipboard 然后打开插件，然后插件会自动更新。
> 注意，不要通过历史记录打开，因为有缓存，不会更新插件

**Comment by muwoo** [comment]
@rebron1900 已修复，

1. 重启rubick 
2. 通过输入框搜索Clipboard 然后打开插件，然后插件会自动更新。

> 注意，不要通过历史记录打开，因为有缓存，不会更新插件
