### ISSUE TITLE
关于快捷键唤醒弹框所显示的内容的一些建议

### ISSUE THREAD

**Issue by GitHubChenLin** [rubickCenter/rubick#303]
**您的功能请求是否与问题相关？ 请简单描述.**
没找到以下选项：
1.关闭搜索框下面的历史记录
![image](https://github.com/rubickCenter/rubick/assets/17680811/2c6a11ab-7c62-4d26-b4fd-a8a1d3448759)

2.快捷键呼出后清除上一次进入的窗口
![image](https://github.com/rubickCenter/rubick/assets/17680811/f38f1d97-d864-45cd-b319-69dd79189312)

**请描述一下您想要的解决方案**
希望提供可以关闭历史使用记录的选项，以及提供自定义唤醒后弹框显示内容的选项

**描述你考虑过的替代方案**

**Comment by muwoo** [comment]
@GitHubChenLin 右击搜索记录，会出现删除菜单：

![image](https://github.com/rubickCenter/rubick/assets/21073039/89e6b51f-2be4-48d1-a654-78e574691a63)

**Comment by yqs112358** [comment]
> @GitHubChenLin 右击搜索记录，会出现删除菜单：
> 
> ![image](https://user-images.githubusercontent.com/21073039/282998169-89e6b51f-2be4-48d1-a654-78e574691a63.png)

这样确实可以删除历史，不过下次打开之后历史又会显示出来。
希望可以增加选项彻底禁止历史使用记录，只留一个搜索框

**Comment by GitHubChenLin** [comment]
> > @GitHubChenLin 右击搜索记录，会出现删除菜单：
> 
> 这样确实可以删除历史，不过下次打开之后历史又会显示出来。 希望可以增加选项彻底禁止历史使用记录，只留一个搜索框😊

yep~，只是想让这个搜索框更简洁一点，所以希望可以隐藏历史使用记录；
然后我的第二个问题也希望可以得到解决，举个例子：每次用快捷键唤醒搜索框之后，使用host插件，修改之后保存，失焦关掉搜索框以及下面的host窗口：
![image](https://github.com/rubickCenter/rubick/assets/17680811/e7352c0f-aa07-41a8-9b3a-d8b9e545a227)
然后重新快捷键唤醒搜索框，此时仍显示之前的host插件。

**Comment by Adammartain** [comment]
我也有这个问题，觉得搜索框简洁一点比较好看。可以提供一个关闭使用记录的选项
