### ISSUE TITLE
m1pro 安装报错

### ISSUE THREAD

**Issue by yangxinSamsara** [rubickCenter/rubick#308]
**描述一下这个bug**
macos m1pro 12.7.1  安装报错

**预期行为**
可以正常安装使用

**截图**
<img width="586" alt="image" src="https://github.com/rubickCenter/rubick/assets/31761016/2b9a1d52-4a24-4970-9dff-96c8176a016d">

<img width="260" alt="image" src="https://github.com/rubickCenter/rubick/assets/31761016/a6e85c83-804d-4033-9251-33a0a3878831">

**Comment by MaxQi** [comment]
在 macOS 14.1.1 上也碰到同样的问题。

**Comment by lemon-tree-sheng** [comment]
14.0 同样的问题

**Comment by muwoo** [comment]
@yangxinSamsara @MaxQi @lemon-tree-sheng #247
