### ISSUE TITLE
用户名超过一定字符时会溢出

### ISSUE THREAD

**Issue by 1811304592** [rubickCenter/rubick#311]
**描述一下这个bug**
用户名超过一定字符时会溢出，导致右侧剪头无法正常显示

**复现方式**
将用户名更改为大于六个字符的用户名

**预期行为**
应当对超出的字符进行隐藏，例如显示 过客是个铁...

**截图**
![image](https://github.com/rubickCenter/rubick/assets/101338461/b42d5ea3-ecf1-44fa-a98b-d347e8cc41a3)

**Comment by layyback** [comment]
fixed
