### ISSUE TITLE
在输入框按退格键会导致ui偏移

### ISSUE THREAD

**Issue by Alanxtl** [rubickCenter/rubick#318]
**描述一下这个bug**
在输入框按退格键会导致ui偏移

**复现方式**
1. Windows 11 22H2系统下，Rubick 4.2.0-beta.1版本
2. 打开rubick窗口
3. 正常输入文字没有问题，但在输入框按退格键ui会发生偏移，无论输入框内是否有文字
4. 下面的截图为我一直按着退格键的效果

**预期行为**
按退格键应该不发生ui偏移

**截图**
![生成](https://github.com/rubickCenter/rubick/assets/25652981/d27ea9a8-8b02-42c6-b14d-df6ce43af318)

**Comment by 1129921824** [comment]
新版本应该是已经修复，可以关闭issue了
