### ISSUE TITLE
在主界面下面的“最近打开”栏目无法打开软件

### ISSUE THREAD

**Issue by 102365478** [rubickCenter/rubick#319]
**描述一下这个bug**
在主界面下面的“最近打开”栏目按回车进入软件会显示”插件已被卸载“

**复现方式**
1. Windows 11 22H2系统下，Rubick 4.2.0-beta.1版本
2. 使用rubick随便打开一个软件
3. 该软件会进入主界面下面的“最近打开”栏目
4. 在主界面下面的“最近打开”栏目按回车进入这个软件
5. 会显示”插件已被卸载“

**截图**
![生成](https://github.com/rubickCenter/rubick/assets/25652981/d82c828c-6ab0-472f-ac57-828fdb875f59)

**Comment by Zhao-yangyang** [comment]
![image](https://github.com/rubickCenter/rubick/assets/59439797/21b4bd98-57d4-4797-ba08-8c6032b961bd)
我这里也是，最近打开里面安装的插件可以但是打开过的本地软件再去点就变成了如图

**Comment by lakevilladom** [comment]
希望能保留之前的垂直列表显示方式

**Comment by muwoo** [comment]
@102365478 @lakevilladom @Zhao-yangyang 最新版本已修复
