### ISSUE TITLE
我把超级面板移除了， 再次启动， 就报如下错误

### ISSUE THREAD

**Issue by coolflameSLZ** [rubickCenter/rubick#323]
![9bece5aa89d0ec499aa03667a7e0747](https://github.com/rubickCenter/rubick/assets/26346479/3a5f1008-544d-48a8-9110-ae0b5a7e37c5)

A JavaScript error occurred in the main process
ncaught Exception:
Error: Cannot find module 'arch'
Require stack:
C:\Users\sunli\AppData Roaming\rubick rubick-plugins-new\node mo...lwindows.jsC:\Users\sunli\AppData Roaming\rubick rubick-plugins-new node modul... index.js
C:(Users(sunli\AppData Roaming rubick rubick-plugi... clipboardy-clipboard.class.js
C:Users sunli\AppData Roaming rubickrubick-plugins-n... provider-registry.class.js
C:\Users\sunli\AppData Roaming\rubick rubick-plugins-new nod... sleep.function.js
C:\Users(sunli AppData Roaming rubick rubick-plugins-new nod... keyboard.classjs
C:Users(sunli AppData Roaming\rubick\rubick-plugins-new node modul... indexjs
C:Users sunli\AppData Roaming\rubick rubick-plugins-new node module... main.js复setD:\Program Files\rubick resourceslapp.asarlindex.js
at node:internal/modules/cjs/loader:1084:15
at Function. resolveFilename (node:electron/js2c/browser init:2:117285)
at node:internal/modules/cis/loader:929:27at Function.load (node:electron/is2c/asar bundle:2:13330)at Module.require (node:internal/modules/cjs/loader:1150:19)at require (node:internal/modules/cis/helpers:110:18)
at Object.<anonymous>
(C:Users sunli\AppData Roaming rubick rubick-plugins-new node modules r...14at Module. compile (node:internal/modules/cjs/loader:1271:14)at Object..js (node:internal/modules/cis/loader:1326:10)at Module.load (node:internal/modules/cis/loader:1126:32)

**Comment by muwoo** [comment]
@coolflameSLZ 重启一下 rubick 试试看
如果重启rubick 不行，尝试删除目录：`C:\Users\sunli\AppData Roaming\rubick\rubick-plugins-new` 然后再重启
