### ISSUE TITLE
如何获取utools插件，并转到 rubick 上？

### ISSUE THREAD

**Issue by huameiwei-vc** [rubickCenter/rubick#325]
如何获取utools插件，并转到 rubick 上？
我看到问题了有个转换的办法，但是如何获取到utools 上的upx文件呢？
对小白来说，有没有简单的办法可以一键转换的吗

**Comment by muwoo** [comment]
@huameiwei-vc 目前没有一键转换的方法，utools 上的 upx 文件这里有个地址可以看到一些：https://github.com/marsvet/uTools-plugins-collection
