### ISSUE TITLE
本地启动，拖拽文件的时候，rubick就隐藏，无法拖拽进去

### ISSUE THREAD

**Issue by monkey6** [rubickCenter/rubick#330]
**描述一下这个bug**
本地启动功能，当去拖拽文件的时候，rubick就隐藏了，无法拖拽进来。

**Comment by monkey6** [comment]
解决了，你得先拖拽着文件，然后在快捷键启动rubick。感觉不方便，希望能够打开rubick本地启动界面，然后直接拖拽过来。

**Comment by muwoo** [comment]
@monkey6 rubick 右上角有个 ... 点开后，钉住 rubick 就会常驻在桌面
![image](https://github.com/rubickCenter/rubick/assets/21073039/13b18625-3946-457b-af37-5da43a1e5b57)
