### ISSUE TITLE
用编程化方式自带的npm版本比较低，是会存在漏洞的吧，最新的npm已经不支持这种使用了

### ISSUE THREAD

**Issue by yourenyouyu** [rubickCenter/rubick#339]
**描述一下这个bug**
清楚而简洁地描述了错误是什么

**复现方式**

**预期行为**
清晰简明地描述了您预期的发生。

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。

**Comment by muwoo** [comment]
@yourenyouyu 是的，编程式的 `npm` 新版本已经被弃用了，但是在 rubick 中用是没问题的。如果不用编程式的 `npm` 那就需要用户本地电脑上装 `rubick` 的同时也需要装 `node` 环境，这有点劝退了。
