### ISSUE TITLE
插件搜索能否支持不区分大小写？

### ISSUE THREAD

**Issue by rippergs** [rubickCenter/rubick#340]

**Comment by muwoo** [comment]
@rippergs 
![image](https://github.com/rubickCenter/rubick/assets/21073039/ecd3e466-8271-4f38-b043-c6805203f2f8)

本来就没有区分大小写呀？可以提供一下你的操作截图

**Comment by RipperTs** [comment]
不是这个搜索哦，是插件市场中的搜索，如果插件名是`Oppo`,搜索`oppo`是无法查询到的

**Comment by muwoo** [comment]
@RipperTs 已修复
