### ISSUE TITLE
本地npm link后安装插件一直卡加载

### ISSUE THREAD

**Issue by youyou-sudo** [rubickCenter/rubick#344]
### Discussed in https://github.com/rubickCenter/rubick/discussions/343

<div type='discussions-op-text'>

<sup>Originally posted by **jerryyang-git** January 31, 2024</sup>
看到了 Rubick 这个项目能很方便的把 utools 的插件移植过去，尝试了下，根据文档更改了 utools 的文件，并且 `npm link` 成功了
查看 `C:\Users\your-user\AppData\Roaming\npm\node_modules` 这个目录也有名为 `name` 的文件夹链接

但我在`开发者`菜单输入了 `name` 的值，也就是这个包的名字，但安装按钮一直在加载，一直安不上，不知道什么问题
使用的是[能不能好好说话-v0.0.1.zip](https://github.com/rubickCenter/rubick/files/14101033/-v0.0.1.zip)插件解包并修改 `plugin.json` 为Rubick需要的 `package.json` 格式
</div>

**Comment by muwoo** [comment]
@jerryyang-git 

插件名称改成 插件代码的路径试试看

![image](https://github.com/rubickCenter/rubick/assets/21073039/14e6e09a-4672-46ac-aeef-a8d96fab32b4)
