### ISSUE TITLE
能否添加一个关闭使用记录的功能

### ISSUE THREAD

**Issue by blankzsh** [rubickCenter/rubick#345]
对于习惯utools的用户来说使用记录有点碍眼了，所以建议添加一个关闭一个使用记录的功能

**Comment by muwoo** [comment]
@blankzsh 

在基本设置里面添加了一个 `关键词搜索记录` 开关，可以选择性关闭，**关闭后，重启 rubick 则不会出现历史记录**

![image](https://github.com/rubickCenter/rubick/assets/21073039/a72aad2b-f152-4644-b313-6297ff866f7d)
