### ISSUE TITLE
Ubuntu21.04下无法启动

### ISSUE THREAD

**Issue by XXTX-TOP** [rubickCenter/rubick#36]
我在ubuntu21.04）实体机安装，非wsl等提示这个：
A JavaScript error occurred in the main process Uncaught Exception: Error: libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846) at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18) at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073) at Module.load (internal/modules/cjs/loader.js:935:32) at Module._load (internal/modules/cjs/loader.js:776:14) at Function.f._load (electron/js2c/asar_bundle.js:5:12913) at Module.require (internal/modules/cjs/loader.js:959:19) at require (internal/modules/cjs/helpers.js:88:18) at Object.<anonymous> (/snap/rubick2/x1/resources/app.asar/node_modules/iohook/index.js:24:21) at Module._compile (internal/modules/cjs/loader.js:1078:30) 

系统自带的有，'(libxkbcommon-x11-0 已经是最新版 (1.0.3-2))'

**Comment by muwoo** [comment]
@SOVLOOKUP 有空帮忙解决一下

**Comment by tcsnzh** [comment]
这是我的环境，看看能不能帮到你：

`

tcsnzh@ubuntuzh:~$ apt search libxkb*
正在排序... 完成
全文搜索... 完成  
gir1.2-xkl-1.0/focal 5.4-4 amd64
  X Keyboard Extension high-level API - introspection data

libxkbcommon-dev/focal,now 0.10.0-1 amd64 [已安装，自动]
  library interface to the XKB compiler - development files

libxkbcommon-doc/focal,focal 0.10.0-1 all
  library interface to the XKB compiler - documentation

libxkbcommon-x11-0/focal,now 0.10.0-1 amd64 [已安装，自动]
  library to create keymaps with the XKB X11 protocol

libxkbcommon-x11-dev/focal 0.10.0-1 amd64
  library to create keymaps with the XKB X11 protocol - development files

libxkbcommon0/focal,now 0.10.0-1 amd64 [已安装，自动]
  library interface to the XKB compiler - shared library

libxkbfile-dev/focal 1:1.1.0-1 amd64
  X11 keyboard file manipulation library (development headers)

libxkbfile1/focal,now 1:1.1.0-1 amd64 [已安装，自动]
  X11 keyboard file manipulation library

libxklavier-dev/focal 5.4-4 amd64
  Development files for libxklavier

libxklavier16/focal,now 5.4-4 amd64 [已安装，自动]
  X Keyboard Extension high-level API

`

**Comment by tcsnzh** [comment]
> 这是我的环境，看看能不能帮到你：
> 
> `
> 
> tcsnzh@ubuntuzh:~$ apt search libxkb*
> 正在排序... 完成
> 全文搜索... 完成
> gir1.2-xkl-1.0/focal 5.4-4 amd64
> X Keyboard Extension high-level API - introspection data
> 
> libxkbcommon-dev/focal,now 0.10.0-1 amd64 [已安装，自动]
> library interface to the XKB compiler - development files
> 
> libxkbcommon-doc/focal,focal 0.10.0-1 all
> library interface to the XKB compiler - documentation
> 
> libxkbcommon-x11-0/focal,now 0.10.0-1 amd64 [已安装，自动]
> library to create keymaps with the XKB X11 protocol
> 
> libxkbcommon-x11-dev/focal 0.10.0-1 amd64
> library to create keymaps with the XKB X11 protocol - development files
> 
> libxkbcommon0/focal,now 0.10.0-1 amd64 [已安装，自动]
> library interface to the XKB compiler - shared library
> 
> libxkbfile-dev/focal 1:1.1.0-1 amd64
> X11 keyboard file manipulation library (development headers)
> 
> libxkbfile1/focal,now 1:1.1.0-1 amd64 [已安装，自动]
> X11 keyboard file manipulation library
> 
> libxklavier-dev/focal 5.4-4 amd64
> Development files for libxklavier
> 
> libxklavier16/focal,now 5.4-4 amd64 [已安装，自动]
> X Keyboard Extension high-level API
> 
> `

- [ ] 我是Ubuntu20.04

**Comment by tcsnzh** [comment]
这是我的Ubuntu20.04所安装的，看看能不能帮到你。

`
tcsnzh@ubuntuzh:~$ apt search libxkb*
正在排序... 完成
全文搜索... 完成  
gir1.2-xkl-1.0/focal 5.4-4 amd64
  X Keyboard Extension high-level API - introspection data

libxkbcommon-dev/focal,now 0.10.0-1 amd64 [已安装，自动]
  library interface to the XKB compiler - development files

libxkbcommon-doc/focal,focal 0.10.0-1 all
  library interface to the XKB compiler - documentation

libxkbcommon-x11-0/focal,now 0.10.0-1 amd64 [已安装，自动]
  library to create keymaps with the XKB X11 protocol

libxkbcommon-x11-dev/focal 0.10.0-1 amd64
  library to create keymaps with the XKB X11 protocol - development files

libxkbcommon0/focal,now 0.10.0-1 amd64 [已安装，自动]
  library interface to the XKB compiler - shared library

libxkbfile-dev/focal 1:1.1.0-1 amd64
  X11 keyboard file manipulation library (development headers)

libxkbfile1/focal,now 1:1.1.0-1 amd64 [已安装，自动]
  X11 keyboard file manipulation library

libxklavier-dev/focal 5.4-4 amd64
  Development files for libxklavier

libxklavier16/focal,now 5.4-4 amd64 [已安装，自动]
  X Keyboard Extension high-level API
`

**Comment by SOVLOOKUP** [comment]
为解决这个问题，这段时间我研发了 [rubickbase](https://github.com/SOVLOOKUP/rubickbase)，以直接替换 iohook 依赖，因此这个问题将很快能得到解决～

**Comment by muwoo** [comment]
@XXTX-TOP 已修复
