### ISSUE TITLE
需要【翻译】功能

### ISSUE THREAD

**Issue by nathandingx** [rubickCenter/rubick#367]
**您的功能请求是否与问题相关？ 请简单描述.**
有时候需要翻译，但没有翻译插件，不能快速的把复制的文件翻译成中文

**请描述一下您想要的解决方案**
制作翻译插件，或者系统原生自带翻译插件；复制后文字后，能快速的双向切换翻译成默认语言

**描述你考虑过的替代方案**
无，上方解决非常完美

**Comment by muwoo** [comment]
@nathandingx 沙拉查词插件不就是翻译吗？

**Comment by nathandingx** [comment]
我之前卸载utools换的咱们这款工具，可能是误把PowerToys弹窗当作rubick弹窗了，搞错了，抱歉
