### ISSUE TITLE
插件市场一片空白

### ISSUE THREAD

**Issue by xiaoxing365** [rubickCenter/rubick#393]
**描述一下这个bug**
清楚而简洁地描述了错误是什么

**复现方式**
1. Go to 插件市场

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。
![PixPin_2024-09-26_01-18-20](https://github.com/user-attachments/assets/f6b77a97-b90a-4bfc-b420-a6e156797e8a)

**Comment by a7021** [comment]
遇到一样的问题，怎么解决呢？？

**Comment by muwoo** [comment]
![image](https://github.com/user-attachments/assets/88329596-770f-4d9d-8abc-c6bbbc6b0e86)
这个 CSDN 把我的 JSON 给重定向了😭

**Comment by muwoo** [comment]
晚点我要换个源白嫖了，这个 sg CSDN。

**Comment by JustNowJustLike** [comment]
才发现这个utools的开源替代，非常棒，但是插件市场是空的

**Comment by narugakuru** [comment]
一样的问题，node 18，系统w11，X64版本，打开插件市场完全空白
还有一个很奇怪的地方是它识别不到我的VSCode，即使我输入全称也识别不到
![image](https://github.com/user-attachments/assets/6d2ec8a8-906c-4185-92cc-63a97b0ec3bf)

**Comment by muwoo** [comment]
@narugakuru @JustNowJustLike @a7021 @xiaoxing365 
已修复，更新最新版本可以解决。如果暂时无法更新可以这么解决：
![image](https://github.com/user-attachments/assets/0d532ecb-282d-4e98-83a6-220553a81676)

替换成：https://gitee.com/monkeyWang/rubickdatabase/raw/master
