### ISSUE TITLE
rubick-database仓库无了，导致插件市场一片空白

### ISSUE THREAD

**Issue by 96368a** [rubickCenter/rubick#394]
**描述一下这个bug**
gitcode的[rubick-database](https://gitcode.net/rubickcenter/rubick-database)仓库无了，导致插件市场一片空白

**复现方式**
登录csdn访问https://gitcode.net/rubickcenter/rubick-database显示404
应用插件市场一片空白

**预期行为**
应用插件市场一片空白

**截图**
![图片](https://github.com/user-attachments/assets/7981959c-2b16-4b98-b534-5d219de68a34)

**Comment by muwoo** [comment]
@96368a 已修复，更新最新版本可以解决。如果暂时无法更新可以这么解决：
![image](https://github.com/user-attachments/assets/0d532ecb-282d-4e98-83a6-220553a81676)

替换成：https://gitee.com/monkeyWang/rubickdatabase/raw/master

**Comment by ViCrack** [comment]
![image](https://github.com/user-attachments/assets/00ac9ed6-3196-4a81-b8a0-b5a639e0e45f)

提一下，文档上面还没修改
