### ISSUE TITLE
插件面板一片空白

### ISSUE THREAD

**Issue by bzw1204** [rubickCenter/rubick#395]
**描述一下这个bug**
清楚而简洁地描述了错误是什么

**复现方式**

**预期行为**
清晰简明地描述了您预期的发生。

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。
![image](https://github.com/user-attachments/assets/2458d1e5-5856-4f7a-aefc-7fc8e99b4072)

**Comment by clevertension** [comment]
里面的gitee路径有错误, 我已经提交PR了
