### ISSUE TITLE
我在爱尔兰，点击下载插件一直转圈，海外是下载不了插件吗？

### ISSUE THREAD

**Issue by Adammartain** [rubickCenter/rubick#401]

**Comment by yangxiaoge** [comment]
+1

**Comment by muwoo** [comment]
@Adammartain @yangxiaoge 可能是 npm 源默认代理到国内的原因，需要调整一下这里的设置：

![image](https://github.com/user-attachments/assets/2bb7f98a-c9ed-4ced-a3f6-fde4436408df)

**Comment by Adammartain** [comment]
感谢！但是调整成什么呢，不太懂，有没有默认可用的呀

**Comment by Adammartain** [comment]
![aec1daa5e28af12697af7d6e0b897f7](https://github.com/user-attachments/assets/66e42036-a186-42a3-b807-94367d92f5d2)

**Comment by muwoo** [comment]
@Adammartain databaseUrl 设置成这个：https://gitee.com/monkeyWang/rubickdatabase/raw/master

**Comment by Adammartain** [comment]
@muwoo 生效了！谢谢大佬的无私帮助

**Comment by muwoo** [comment]
@Adammartain 插件可以使用了么？

**Comment by Adammartain** [comment]
@muwoo  大佬真是料事如神，安装成功但是用不了。。而且部分插件如超级面板还是安装不了

**Comment by muwoo** [comment]
![image](https://github.com/user-attachments/assets/60e75804-ec82-4b9b-9379-a80bec84bf82)

试试看zhe'ge这个插件能不能用，有些插件没维护了，可能有点兼容性问题

**Comment by Adammartain** [comment]
@muwoo 用不了，不显示
![8bccd42bc4b640354267bae77768522](https://github.com/user-attachments/assets/48e5ffa3-f7a8-4eba-93b6-5592ac5acbae)

**Comment by Adammartain** [comment]
@muwoo 可以使用！我之前没开“显示关键词搜索记录”，开了之后就正常显示插件了（虽然我喜欢不开的样式，比较简洁），感谢大佬的帮助！
