### ISSUE TITLE
给点建议

### ISSUE THREAD

**Issue by sl514** [rubickCenter/rubick#45]
1. 关键字 大小写字母不要区分
2. windows下拖动搜索框会变大依旧存在。
3. 尽量使用国内的包，国内用github还是有点难度的。
4. 希望增加一个 rubick类的内置方法描述。  比如: rubick.showNotification 好用很好用，但是不看demo 都不知道有这么个方法。

**Comment by muwoo** [comment]
@sl514 rubick 已更新至2.x 版本，已修复
