### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by wenger67** [rubickCenter/rubick#51]
一直编译不成功
iohook   这个prebuild就一直下载不成功
robotjs   对应git仓库最新版本三0.6.0，但是本仓库为何要去下0.6.1，也是下载不成功

**Comment by SOVLOOKUP** [comment]
需要科学上网，iohook 和 robotjs 在安装的时候都需要下载预编译的二进制文件

我们已经写了 [rubickbase](https://github.com/SOVLOOKUP/rubickbase) 来替代这两个依赖，更新会在将来的版本中到来

**Comment by renmu123** [comment]
真的是编译起来太痛苦了

**Comment by SOVLOOKUP** [comment]
我感同身受 敬请期待接下来的变化

**Comment by wdlnydhcg** [comment]
替换了吗？咋还是安装不上？ @SOVLOOKUP

**Comment by SOVLOOKUP** [comment]
> 替换了吗？咋还是安装不上？ @SOVLOOKUP 

我们并没有对依赖进行简单的替换，而是基于 Rust + TypeScript + Vue3 和最新的 Electron15 重构了整个项目，现在的进程在 50% 左右

**Comment by PurityChan** [comment]
我已经从零用TypeScript +Vue3+Electron15搭建了下环境，直接使用  rubickbase 库 编译运行报错，如果使用最简单的node工程，rubickbase 确实好的，是啥情况呀 @SOVLOOKUP

**Comment by SOVLOOKUP** [comment]
> 我已经从零用TypeScript +Vue3+Electron15搭建了下环境，直接使用 rubickbase 库 编译运行报错，如果使用最简单的node工程，rubickbase 确实好的，是啥情况呀 @SOVLOOKUP

可以到 rubickbase 仓库提一个 issue 描述一下具体的错误

**Comment by muwoo** [comment]
@PurityChan @PurityChan @wenger67 rubick 2.0 已发布，感谢持续关注，2.0 移除了 robot.js 和iohook。所依赖的功能通过系统插件替代，比如超级面板，欢迎前往体验
