### ISSUE TITLE
everything支持

### ISSUE THREAD

**Issue by renmu123** [rubickCenter/rubick#54]
希望可以支持everything。

设置中的“本地搜索启动”设置项，好像不管开关都没什么区别

**Comment by muwoo** [comment]
@renmu123 macos 已通过 mverything 插件支持，win还在努力

**Comment by renmu123** [comment]
感觉有两种方法
1. 调用 everything 的 http 接口
2. 调用 everything 的 sdk

**Comment by muwoo** [comment]
@renmu123 everything 有 http 接口吗

**Comment by muwoo** [comment]
看了一下，http接口需要预先装everything 这个成本有点大

**Comment by renmu123** [comment]
> 看了一下，http接口需要预先装everything 这个成本有点大

或者也可以调用everything的cli，但是这样搜索时会跳出everything的程序

**Comment by flyinghail** [comment]
> 看了一下，http接口需要预先装everything 这个成本有点大

SDK 更合理，http 得在 everything 里面默认是关的，得手动启用，增加了无畏的操作。另外之前 everything 报出过 http 安全漏洞，打开增加了风险。
像 wox 之类的 windows 工具，都需要预先装 everything。
utools 的搜索每次启动第一次搜索要跑一遍索引，如果预先装好了everything 就可以直接用，不用跑索引了，所以我都是会单独装 everything。
预先装 everything 没什么不好的，还能主动升级。

**Comment by renmu123** [comment]
> > 看了一下，http接口需要预先装everything 这个成本有点大
> 
> SDK 更合理，http 得在 everything 里面默认是关的，得手动启用，增加操作。另外之前 everything 报出过 http 安全漏洞，打开增加了风险。 像 wox 之类，都需要预先装 everything。 utools 每次开机第一次搜索用自带的 everything 跑一遍索引，如果预先装好了独立的 everything 就不用索引可以直接用，所以我一直都会单独装 everything。 预先装 everything 没什么不好的，还能主动升级。

是sdk更加好，但是node能否操作dll是一个问题，虽然不清楚node的一些相关操作包能支持到什么程度

**Comment by flyinghail** [comment]
> 是sdk更加好，但是node能否操作dll是一个问题，虽然不清楚node的一些相关操作包能支持到什么程度

不知道这个行不行：https://www.npmjs.com/package/electron-node-ffi

**Comment by flyinghail** [comment]
发现一个新的项目 https://github.com/naaive/orange
可以使用 @tauri-apps/api 通信

**Comment by KleinPan** [comment]
这个现在有最新情况了吗？

**Comment by muwoo** [comment]
@KleinPan 暂时还木有，限于个人能力，我还得再调研调研

**Comment by muwoo** [comment]
@KleinPan @renmu123 @flyinghail windows 已有 everything 插件支持；本地启动已支持。可以下载最新版rubick体验
