### ISSUE TITLE
 Windows下有的时候没法搜索到中文的软件

### ISSUE THREAD

**Issue by someone120** [rubickCenter/rubick#61]
**描述一下这个bug**
Windows下有的时候没法搜索到中文的软件

**复现方式**
emm就直接搜索

**预期行为**
能看到我想要的软件

**截图**
![image](https://user-images.githubusercontent.com/47704813/135240254-c0499343-fc35-4533-bc9c-7409eea5fad9.png)
![image](https://user-images.githubusercontent.com/47704813/135240303-e9062d89-9eaf-4e18-9afb-f728ff116bc1.png)

**Comment by someone120** [comment]
顺便吐槽一下拼音对多音字的识别不准确，有考虑用第三方库吗

**Comment by SOVLOOKUP** [comment]
这个软件有注册到开始菜单里吗？ 目前 windows 下是搜索的菜单目录

rubick是社区共建的项目，多音字的问题，非常欢迎来提 PR 解决哦～

**Comment by someone120** [comment]
> 这个软件有注册到开始菜单里吗？ 目前 windows 下是搜索的菜单目录
> 
> rubick是社区共建的项目，多音字的问题，非常欢迎来提 PR 解决哦～

有注册到开始菜单里，搜不到菜单目录下的文件夹中的中文软件

**Comment by someone120** [comment]
> > 这个软件有注册到开始菜单里吗？ 目前 windows 下是搜索的菜单目录
> > rubick是社区共建的项目，多音字的问题，非常欢迎来提 PR 解决哦～
> 
> 有注册到开始菜单里，搜不到菜单目录下的文件夹中的中文软件

准确来说是用拼音搜不到
