### ISSUE TITLE
快捷键设置后报错

### ISSUE THREAD

**Issue by Privauto** [rubickCenter/rubick#64]
**描述一下这个bug**
设置该快捷键后报错误，再次启动时报同样的错误

**复现方式**
1.将快捷键设置为Ctrl+Shift
2.使用该快捷键
3.Error

**预期行为**
希望将显示和隐藏的快捷键设置为Alt+空格或者Ctrl+Shift

**截图**
![V81TH55PKF5$A1HM5_VU8}L](https://user-images.githubusercontent.com/36581456/136399009-438c5e14-9c93-49a3-b6f3-64d709806810.png)

**Comment by muwoo** [comment]
@Privauto 已修复，安装最新版本，不过目前不支持多修饰键，仅支持单修饰键，比如 ctrl+r,shift+r 但不支持ctrl+shift+r
