### ISSUE TITLE
为啥不ban猛犸？建议拼音库用pinyin取代jian-pinyin，提高多音字准确性

### ISSUE THREAD

**Issue by unisgn** [rubickCenter/rubick#67]
看了下项目里处理拼音用了jian-pinyin这个库。看了下这个库似乎更合适web应用，在体积上面比较有优势，但是没有处理多音字准确性。
建议使用 [pinyin](https://www.npmjs.com/package/pinyin) 这个库，它会分词根据词组来匹配，能提高多音字准确性，更适合桌面应用。

**Comment by muwoo** [comment]
@unisgn pinyin 这个库用了一下，打包的时候有点bug，就弃用了
