### ISSUE TITLE
修改插件安装目录

### ISSUE THREAD

**Issue by gclm** [rubickCenter/rubick#73]
**您的功能请求是否与问题相关？ 请简单描述.**
1. 操作环境: mac
目前插件安装目录为用户根目录：/Users/gclm/xxx-plugins，如果插件安装的比较多的话那会创建很多目录，对用户来说管理比较麻烦。这个需要个人建议优化一下

**请描述一下您想要的解决方案**
在用户根目录创建一个目录，如/Users/gclm/rubick-plugins，安装的插件全部在这个目录里面，这样方便用户管理，或者想utools一样，放到一个我看不到的地方

**描述你考虑过的替代方案**
无

**Comment by muwoo** [comment]
@gclm 已修改，rubick2.0全新发布，欢迎体验
