### ISSUE TITLE
安装不了插件

### ISSUE THREAD

**Issue by LinHQ1999** [rubickCenter/rubick#74]
**描述一下这个bug**
用的 Windows11，打开插件中心显示 _no data_ 。

**复现方式**
1. 进入“插件中心”。

**预期行为**
能够安装插件。

**截图**
![image](https://user-images.githubusercontent.com/50328516/145720626-28b22db6-5f4a-4362-b06b-ee7b233ae74f.png)

**Comment by muwoo** [comment]
@LinHQ1999 rubick 由于本人囊中羞涩，服务器已欠费。目前已基于 npm 重新设计了一套插件管理体系，另外为了减少按照包的大小，把超级面板抽离成了系统插件支持。欢迎前往体验 [Rubick 2.0](https://github.com/rubickCenter/rubick2)

**Comment by LinHQ1999** [comment]
明白了🤣

**Comment by muwoo** [comment]
@LinHQ1999 rubick2 已合入rubick master 主干，未来还是在这个项目维护，不需要再切到 rubick2.0 上了
