### ISSUE TITLE
mac 平台无法修改默认快捷键

### ISSUE THREAD

**Issue by gclm** [rubickCenter/rubick#77]
**描述一下这个bug**
mac 平台无法修改默认快捷键

版本：v2.0.1-beta.8
**复现方式**
1. 打开软件把默认打开窗口快捷键修改成 commond + 空格，结果无法修改

**预期行为**
修改成功

**截图**
![image](https://user-images.githubusercontent.com/27618687/147437988-bede4869-05f6-4935-8342-4001911b22e3.png)

**Comment by muwoo** [comment]
@gclm  已修复

**Comment by gclm** [comment]
还是不行啊。输入没反应啊
![image](https://user-images.githubusercontent.com/27618687/147545123-10f14ef8-1b34-4374-8981-2ba778e0f8d4.png)

**Comment by gclm** [comment]
环境：mac 12.1 (21C52)

**Comment by muwoo** [comment]
@gclm 这个不是input，你直接按键就可以了。比如你要设置 `option+space` ,那你就点击到这个设置项，然后按下`option+space`

**Comment by gclm** [comment]
![IMG_8933](https://user-images.githubusercontent.com/27618687/147633172-22d8863b-5116-41c2-9bb1-c79f6c3b7eee.JPG)
就是按键按不动，

**Comment by gclm** [comment]
我按的是command + v

**Comment by muwoo** [comment]
`/Users/${your username}` 目录下 `rubick-config.json` 文件删除一下再重启试试看

![image](https://user-images.githubusercontent.com/21073039/147633517-e4aeac4a-1d0c-4bbd-bbfd-588ec7c175f7.png)

**Comment by muwoo** [comment]
> 我按的是command + v

这个不行的，存在冲突

**Comment by muwoo** [comment]
@gclm 尝试使用 `option, alt, shift, ctrl` 替代

**Comment by gclm** [comment]
好吧，我看utools 还可以使用command + 空格。但是发现rubick 无法使用这个快捷键，

**Comment by gclm** [comment]
> @gclm 尝试使用 `option, alt, shift, ctrl` 替代

使用 option + 空格倒是正常

**Comment by vfr456** [comment]
v4.2.1  command + space 仍然不会被设置快捷键响应 （在macos设置里已经关闭了“聚焦”的快捷键）
