### ISSUE TITLE
rubick latest version 无法获取诸如 terminal (微软终端) 的 windows 软件

### ISSUE THREAD

**Issue by radiorz** [rubickCenter/rubick#79]
**描述一下这个bug**
清楚而简洁地描述了错误是什么

**复现方式**
- rublick 2.0.1-beta.13

1. alt+r 唤出rubick
2. 输入 terminal 
3.  See error : 没有显示 windows terminal 等软件

**预期行为**
希望可以完整看到 微软商店 下载安装的所有的应用
并且添加 appData 的应用
现在源代码似乎只有 programdata 的应用而没有 用户 appdata 的应用

**截图**
![image](https://user-images.githubusercontent.com/24271959/148871964-ac597995-4d6b-4d38-9364-cdcbd454cc66.png)

**解决方案 ** 
windowsApp 路径我不知道怎么添加 
但是 appData是这样的:

```js
const path = require("path");
const os = require("os");
const programData = path.resolve("C:/ProgramData");
const appData = path.join(os.homedir(), "./AppData/Roaming");

 const    startMenus = [
      path.join(programData, "Microsoft/Windows/Start Menu/Programs"),
      path.join(appData, "Microsoft/Windows/Start Menu/Programs"),
]

```

**Comment by muwoo** [comment]
@radiorz 已支持：https://github.com/rubickCenter/rubick/commit/bdae8c280b67c63e6c69332ae66b37e99374392d

感谢您的建议！

![image](https://user-images.githubusercontent.com/21073039/148880595-84db84dd-7a22-4bac-8687-2ab76a1612cd.png)

**Comment by muwoo** [comment]
@radiorz 请使用最新的 rubick 版本 2.0.1-beta.15
