### ISSUE TITLE
window 点击搜索框没有反应

### ISSUE THREAD

**Issue by hansonfang** [rubickCenter/rubick#80]
**描述一下这个bug**
搜索框没有反应，无法输入，右侧图标点击没有反应

**复现方式**
打开搜索框，点击

**预期行为**
点击右侧图标弹出插件市场

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。

**Comment by muwoo** [comment]
@hansonfang 是windows吗？麻烦提供一下 rubick 版本 和 win 版本

**Comment by muwoo** [comment]
@hansonfang 使用的是安装包还是自己跑 `dev` 运行起来的本地代码？

**Comment by hansonfang** [comment]
> @hansonfang 使用的是安装包还是自己跑 `dev` 运行起来的本地代码？

安装包

**Comment by elxy** [comment]
我也遇到这个问题了

**Comment by muwoo** [comment]
@elxy @hansonfang  尝试一下新版本：https://github.com/rubickCenter/rubick/releases/tag/v2.0.1-beta.16 修复了这个问题

**Comment by elxy** [comment]
> @elxy @hansonfang  尝试一下新版本：https://github.com/rubickCenter/rubick/releases/tag/v2.0.1-beta.16 修复了这个问题

新版本报错：
![brick_error.jpg](https://s2.loli.net/2022/01/14/AqBo58t39KLFTnX.jpg)

**Comment by muwoo** [comment]
@elxy 很高兴收到您的反馈，已修复，之前是因为 `github actions` 构建一直失败，我换了 `windows-2022` 来构建。没想到构建产物有问题，可以重新下载一下安装包再试试

**Comment by elxy** [comment]
> @elxy 很高兴收到您的反馈，已修复，之前是因为 `github actions` 构建一直失败，我换了 `windows-2022` 来构建。没想到构建产物有问题，可以重新下载一下安装包再试试

现在可以正常运行了，辛苦辛苦~~
