### ISSUE TITLE
长按 alt+ R 会导致窗口不断向下拉长

### ISSUE THREAD

**Issue by radiorz** [rubickCenter/rubick#83]
**描述一下这个bug**
版本: beta.16
长按 alt+ R 会导致窗口不断向下拉长

**复现方式**
1. 打开软件
2. 长按 alt+r 不松开
3. See error

**预期行为**
快捷键不拉长窗口

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/24271959/149613999-e2d20a53-6346-4690-874b-b7aed4ec740b.png)

**Comment by muwoo** [comment]
@radiorz 已修复
