### ISSUE TITLE
mac端性能优化

### ISSUE THREAD

**Issue by gclm** [rubickCenter/rubick#88]
mac端感觉卡卡的，没有utools 用起来流畅感强而且资源占用比utools高

![image](https://user-images.githubusercontent.com/27618687/153553017-767ae8b5-01ef-4f59-a7fe-ad9ad78d296a.png)
![image](https://user-images.githubusercontent.com/27618687/153553047-7ec01e8e-5591-4a1e-8996-664ac2143790.png)

**Comment by gitlyp** [comment]
附议 确实卡卡的 有点难搞  
utools丝滑 但是商业化了

**Comment by muwoo** [comment]
体验一下新版本
