### ISSUE TITLE
插件的 setExpendHeight 功能与实际不符

### ISSUE THREAD

**Issue by renmu123** [rubickCenter/rubick#89]
**描述一下这个bug**
插件的 setExpendHeight 函数功能与描述不符，应该要修改插件窗口的高度值而非整个组件窗口的高度值

当我设置 `rubick.setExpendHeight(0);` 时，窗口会变成这样
![image](https://user-images.githubusercontent.com/26896790/154440388-55fb70a1-a172-4d91-a3b9-f58b875baba6.png)

当我设置 ` rubick.setExpendHeight(100);` ，插件窗口大小为18而非100
![image](https://user-images.githubusercontent.com/26896790/154440786-720a13cf-26cd-445b-bc64-22e570cbabd6.png)

**Comment by muwoo** [comment]
`rubick setExpendHeight` 没有计算搜索框本身的高度。你想要的 `setExpendHeight(0)` 应该写成 `setExpendHeight(60)`

`rubick.setExpendHeight(100)` 应该写成 `rubick.setExpendHeight(160)`.

这是因为搜索框窗口高度为 60
