### ISSUE TITLE
打开 rubick 时， 导致 ctrl+d 无法在终端使用

### ISSUE THREAD

**Issue by yola-0316** [rubickCenter/rubick#91]
**描述一下这个bug**
清楚而简洁地描述了错误是什么

打开 rubick 时， 导致 ctrl+d 无法在终端使用

**复现方式**

1. 启动 rubick
2. mac平台，打开 iterm 或 terminal
3. 在 shell 会话中使用 ctrl+d
4. 没有响应 shell 不能关闭。

**预期行为**
清晰简明地描述了您预期的发生。

ctrl+d 不应该注册为全局快捷键，只应该在 rubick 聚焦时生效。

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。

曾经在其他 [issue](https://github.com/rubickCenter/rubick/issues/77#issue-1088979704) 中看到设置界面有 ctrl+d 相关的快捷键。mac 平台没有显示这个快捷键，因此无从修改快捷键。

<img width="797" alt="image" src="https://user-images.githubusercontent.com/4338052/154792536-c97d8d21-1132-440d-baf2-3a40123da143.png">

**Comment by 956237586** [comment]
windows下也是，我的idea和浏览器收藏的Ctrl+D都没法用了，退出Rubick才行
