### ISSUE TITLE
通过插件市场安装插件时报错 A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by PeiFengBin** [rubickCenter/rubick#92]
**描述一下这个bug** 通过插件市场安装插件时报错 A Javascript error occurred in the main process

> 环境：
> 系统：Windows11专业版21H2
> Rubick版本：2.0.2

**复现方式**
1. 打开插件市场
2. 获取任意插件

**截图**
![error](https://user-images.githubusercontent.com/95644799/156892469-70248b76-589a-4ea3-9e7f-1280e093f1d6.jpg)

**Comment by muwoo** [comment]
@PeiFengBin 请问一下，你本地有安装node吗？如果没有的话，可以参考这篇文档安装一下：https://juejin.cn/post/6844903886541553672

**Comment by PeiFengBin** [comment]
😳😳😳
非常抱歉没有看到使用文档里说的需要nodejs环境，安装完nodejs重启后已解决
万分感谢
