### ISSUE TITLE
文档找不到~

### ISSUE THREAD

**Issue by send010** [rubickCenter/rubick#99]
## 任何开发建议、交流学习都可以
没有交流群吗，很棒的工具

文档找不到~

**Comment by layyback** [comment]
你好，流水线因为某些原因失败了，可以先参考 https://layyback.github.io/rubick/，我们会尽快恢复

**Comment by muwoo** [comment]
@send010 已修复

**Comment by muwoo** [comment]
@send010 交流群加我微信 `anjingde8744` ，我拉你进去
